'use strict';(function(r){if(void 0!==rea.globals._content)console.warn('content: Stop here, cause a second Tampermonkey instance was detected!\nThis can be caused by using "document.write" at Userscripts.\nSee https://code.google.com/p/chromium/issues/detail?id=253388 for more information');else{rea.globals._content=!0;var g;r.Registry=function(){var c={},e=[],a=function(){e=e.filter(function(a){var d=!1;a.r.forEach(function(a){c[a]||(d=!0)});if(d)return!0;a.fn()})},b=function(d,b,e){c[d]=e;a()},
d=function(a){a=c[a];return a instanceof Function?a():a};return{register:b,registerRaw:b,get:d,getRaw:d,require:function(d,b){e.push({r:d,fn:b});a()}}}();var n=function(){var c=function(a){return({}.toString.apply(a).match(/\s([a-z|A-Z]+)/)||[null,a&&"INPUT"===a.nodeName?"HTMLInputElement":"Object"])[1]},e=function(a){if("Object"==c(a)){var b=[],d;for(d in a)a.hasOwnProperty(d)&&b.push(d+":"+e(a[d]));return"{"+b.join(",")+"}"}if("Array"==c(a)){var k=[];a.forEach(function(a){k.push(e(a))});return"["+
k.join(",")+"]"}return void 0===a?"undefined":null===a?"null":"Function"==c(a)?a.toString():'"'+a.toString()+'"'};return{createUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})},processQueue:function(a){for(var b;b=a.shift();)b()},serialize:e,toType:c}}(),y=function(){var c={_content:!0,JSHINT:!0},e=/(webkitStorageInfo|webkitIDB.*|webkitIndexedDB|webkitOfflineAudioContext|webkitAudioContext|webkitURL|webkitSpeech.*|Bluetooth.*|MIDI.*)/;
return function(){var a={},b,d,k=Object.getOwnPropertyNames(window),m=function(a,d){for(;(a=Object.getPrototypeOf(a))&&a!==Object.prototype;)d=d.concat(Object.getOwnPropertyNames(a));return d}(window,[]);b=0;for(d=null;d=m[b];b++)c[d]||e.exec(d)||(2<d.length&&"on"===d.substr(0,2)?a[d]={proto:!0,event:!0}:a[d]={proto:!0});b=0;for(d=null;d=k[b];b++)c[d]||a[d]||e.exec(d)||(a[d]={window:!0});var f={addEventListener:{window:1},alert:{window:1},atob:{window:1},blur:{window:1},btoa:{window:1},clearInterval:{window:1},
clearTimeout:{window:1},close:{window:1},confirm:{window:1},decodeURI:{window:1},decodeURIComponent:{window:1},dispatchEvent:{window:1},encodeURI:{window:1},encodeURIComponent:{window:1},find:{window:1},focus:{window:1},getComputedStyle:{window:1},getSelection:{window:1},isFinite:{window:1},isNaN:{window:1},open:{window:1},openDialog:{window:1},parseFloat:{window:1},parseInt:{window:1},postMessage:{window:1},print:{window:1},prompt:{window:1},removeEventListener:{window:1},resizeBy:{window:1},resizeTo:{window:1},
scroll:{window:1},scrollBy:{window:1},scrollByLines:{window:1},scrollByPages:{window:1},scrollTo:{window:1},setInterval:{window:1},setTimeout:{window:1},stop:{window:1}};Object.keys(f).forEach(function(d){a[d]||(a[d]=f[d])});return a}}(),f=n.createUUID(),v=window.self==window.top,w=0,p,h=function(c){var e=function(){return c.dispatchEvent.apply(c,arguments)},a=function(){return c.addEventListener.apply(c,arguments)},b=function(){return c.removeEventListener.apply(c,arguments)},d=function(a,d){var b=
c.createEvent("MutationEvent");b.initMutationEvent(a,!1,!1,null,null,null,JSON.stringify(d),b.ADDITION);return b},k=function(a,d){var b;a&&(b=l[a])&&(b(d),delete l[a])},m,f,u,g,h=1,l={};return{init:function(b){g||(g=b);u="2P_"+g;f="2C_"+g;a(f,function(a){var b=JSON.parse(a.attrName);"message.response"==b.m?k(b.r,b.a):m&&m(b,b.r?function(a){a=d(u,{m:"message.response",a:a,r:b.r});e(a)}:function(){})},!1)},send:function(a,b,c){if(c){var k=++h;l[h]=c;c=k}else c=null;a=d(u,{m:a,a:b,r:c});e(a)},onMessage:{addListener:function(a){m=
a}},cleanup:function(){b(f,m,!1)}}}(document),x=function(){var c={},e,a=function(a){var d=[],k=[],e=function(){f=k=d=null;delete c[a]},f={postMessage:function(d){h.send("port.message",{response_id:a,value:d})},onMessage:{addListener:function(a){d.push(a)}},onDisconnect:{addListener:function(a){k.push(a)}},disconnect:function(){h.send("port.message",{response_id:a,disconnect:!0});e()}};c[a]={message:function(a){d&&d.forEach(function(d){d(a)})},disconnect:function(a){k&&k.forEach(function(d){d(a)});
e()}};return f};return{message:function(b){var d;b.connect?e&&e(b.destination,a(b.response_id)):(d=c[b.response_id])?b.disconnect?d.disconnect():d.message(b.value):g&&console.warn("ports: unkown id",b.response_id,b)},connect:function(b){var d=n.createUUID();h.send("port.message",{response_id:d,connect:!0,destination:b});return a(d)},onConnect:{addListener:function(a){e=a}}}}(),l=function(){var c,e,a=[],b=[],d=function(){g&&console.log("content: detected DOMContentLoaded "+f);e=!0;window.removeEventListener("DOMContentLoaded",
d,!1);d=null;n.processQueue(a)},k=function(){g&&console.log("content: detected load "+f);c=e=!0;m.cleanup();n.processQueue(b)};window.addEventListener("DOMContentLoaded",d,!1);window.addEventListener("load",d,!1);var m={registerDomListener:function(d){e||c?d():a.push(d)},registerPageListener:function(a){c?a():b.push(a)},forcedLoad:function(){c||e||!k||(g&&console.log("content: use forced load "+f),k(!0))},seen:function(){var a={};a.__defineGetter__("load",function(){return c});a.__defineGetter__("DOMContentLoaded",
function(){return e});return a}(),cleanup:function(){d&&(window.removeEventListener("DOMContentLoaded",d,!1),d=null);k&&(window.removeEventListener("load",k,!1),k=null)}};return m}(),q=function(){return{init:function(c){p.inject("("+p.backup+')(window, document,"'+c+'",'+g+");\n")},cleanup:function(){h.send("cleanup")},next:function(c,e,a){var b={short_id:rea.runtime.short_id};["inIncognitoContext","downloadMode","enforce_strict_mode","use_strong_mode","version"].forEach(function(a){b[a]=c[a]});b.sandbox_allow_getters=
rea.FEATURES.RUNTIME.FIREFOX;g&&(l.seen.load?console.log("content: Start ENV with page loaded "+f):l.seen.DOMContentLoaded?console.log("content: Start ENV with DOMContentLoaded "+f):console.log("content: Start ENV normally "+f));var d=c.scripts.map(function(a){return{header:a.header,storage:a.storage,script:a.script,requires:a.requires,code:a.code}});h.send("next",p.next(f,JSON.stringify(d),n.serialize(e),JSON.stringify(a),JSON.stringify(b),JSON.stringify({}),w,void 0,void 0,void 0,void 0,g,l.seen.load,
l.seen.DOMContentLoaded,p.environment))}}}(),t=function(){var c={registerMenuCommand:function(a){var b=rea.extension.connect("registerMenuCommand");b.onMessage.addListener(function(d){d.run&&null!==b&&a.postMessage("run")});b.onDisconnect.addListener(function(){a.disconnect()});a.onMessage.addListener(function(a){if("register"===a.method){var c=a.name;b.postMessage({method:"registerMenuCommand",name:c,id:f,menuId:f+"#"+c,accessKey:a.accessKey})}});a.onDisconnect.addListener(function(){b.disconnect()})},
openInTab:function(a){var b=rea.extension.connect("openInTab");b.onMessage.addListener(function(d){a.postMessage(d)});b.onDisconnect.addListener(function(){a.disconnect()});a.onMessage.addListener(function(a){if("openTab"==a.method){var c=a.url,e=a.options;"boolean"===typeof e?e={loadInBackground:e}:e||(e={});a=void 0===e.active?void 0===e.loadInBackground?!0:!e.loadInBackground:e.active;e=void 0===e.insert?!0:e.insert;c&&0===c.search(/^\/\//)&&(c=location.protocol+c);b.postMessage({method:"openInTab",
details:{url:c,options:{active:!!a,insert:!!e}}})}else"nameTab"==a.method?b.postMessage({method:"nameTab",name:a.name}):"closeTab"==a.method&&b.postMessage({method:"closeTab"})});a.onDisconnect.addListener(function(){b.disconnect()})},download:function(a){var b=rea.extension.connect("download");b.onMessage.addListener(function(d){a.postMessage(d)});b.onDisconnect.addListener(function(){a.disconnect()});a.onMessage.addListener(function(a){a=a.details;a.url&&"/"===a.url[0]&&(a.url=location.origin+a.url);
b.postMessage({method:"download",details:a,id:f})});a.onDisconnect.addListener(function(){b.disconnect()})},xhr:function(a){var b=rea.extension.connect("xhr");b.onMessage.addListener(function(b){a.postMessage(b)});b.onDisconnect.addListener(function(){a.disconnect()});a.onMessage.addListener(function(a){b.postMessage(a)});a.onDisconnect.addListener(function(){b.disconnect()})},values:function(a){var b=rea.extension.connect("values");b.onMessage.addListener(function(b){a.postMessage(b)});b.onDisconnect.addListener(function(){a.disconnect()});
a.onMessage.addListener(function(a){b.postMessage(a)});a.onDisconnect.addListener(function(){b.disconnect()})}},e={setClipboard:function(a,b){var d=a.content,c=a.info,e=typeof c,g="text",h="text/plain";"object"===e?(c.type&&(g=c.type),c.mimetype&&(h=c.mimetype)):"string"===e&&(g=c);rea.extension.sendMessage({method:"copyToClipboard",data:{content:d,type:g,mimetype:h},id:f},function(){b()})},notification:function(a,b){a.method="notification";rea.extension.sendMessage(a,b)},syntaxCheck:function(a,b){a.method=
"syntaxCheck";rea.extension.sendMessage(a,b)},closeTab:function(a,b){rea.extension.sendMessage({method:"closeTab",id:f},function(a){a.error&&console.warn(a.error);b()})},focusTab:function(a,b){rea.extension.sendMessage({method:"focusTab",id:f},function(a){a.error&&console.warn(a.error);b()})},addStyle:function(a,b){try{var d=document.createElement("style");d.textContent=a.css||"";(document.head||document.body||document.documentElement||document).appendChild(d);b()}catch(c){console.warn("content: error adding style",
c)}},tabsSet:function(a,b){a.method="setTab";rea.extension.sendMessage(a,function(){b()})},tabsGet:function(a,b){a.method="getTab";rea.extension.sendMessage(a,function(a){b(a.data)})},tabsGetAll:function(a,b){a.method="getTabs";rea.extension.sendMessage(a,function(a){b(a.data)})}};return{init:function(){},getApi:function(){var a={};[e,c].forEach(function(b){Object.keys(b).map(function(c){a["GM_"+c]=b[c]})});return a},processMessage:function(a,b,c){if(a=e[a])return a(b,c);c()},processConnect:function(a,
b){var d;if(d=c[a])return d(b)}}}();rea.extension.onMessage.addListener(function(c,e,a){c.id&&c.id!=f?console.warn("content: Not for me! "+f.substr(0,10)+"!="+c.id):"executeScript"==c.method?c.url&&0!==window.location.href.search(c.url)?g&&console.log("exec: URL doesn't match",window.location,c):c.topframe&&!v?g&&console.log("exec: topframe doesn't match",window.self,c):h.send("executeScript",c):"onLoad"==c.method?(document.readyState&&"complete"!==document.readyState||l.forcedLoad(),a({})):v&&("loadUrl"==
c.method?(window.location=c.url,a({})):"reload"==c.method?(window.location.reload(),a({})):"confirm"==c.method?window.setTimeout(function(){var b=window.confirm(c.msg);a({confirm:b})},100):"showMsg"==c.method?window.setTimeout(function(){window.setTimeout(function(){window.alert(c.msg)},1);a({})},100):"setForeignAttr"==c.method?(h.send(c.method,c),a({})):window.console.log("content: unknown method "+c.method))});x.onConnect.addListener(function(c,e){t.processConnect(c,e)});h.onMessage.addListener(function(c,
e){if("document.write"==c.m){var a=document.documentElement;window.setTimeout(function(){a!==document.documentElement&&h.init()},0)}else"port.message"==c.m?x.message(c.a):t.processMessage(c.m,c.a,e)});Registry.require(["page.js"],function(){p=Registry.getRaw("page.js");(function(c,e){g&&console.log("content: Started ("+f+", "+window.location.origin+window.location.pathname+")");if(r.info){var a=r.info;delete r.info;return a.contexters||a.scripts&&a.scripts.length?(q.init(f),h.init(f),e(a)):c()}q.init(f);
h.init(f);var b=1,d=function(){rea.extension.sendMessage({method:"prepare",id:f,raw:[],topframe:v,url:window.location.href},function(a){void 0===a?(g&&console.debug("content: _early_ execution, connection to bg failed -> retry!"),window.setTimeout(d,b),b*=2):a.contexters||a.scripts&&a.scripts.length?e(a):(q.cleanup(),c())})};rea.content.onReady(d)})(function(){g&&console.log("content: disable event processing for "+f);h.cleanup();l.cleanup();q.cleanup()},function(c){w=c.logLevel;g|=60<=w;l.registerDomListener(function(){h.send("DOMContentLoaded")});
l.registerPageListener(function(){h.send("load")});g&&console.log("content: start event processing for "+f+" ("+c.scripts.length+" to run)");t.init(c.script);q.next(c,t.getApi(),y())})})}})(window);
