Registry.require("promise helper i18n xmlhttprequest uri permission".split(" "),function(){var d={DEFAULT:"default",OFF:"off",NATIVE:"native",CHROME:"chrome",NOT_ENABLED:"not_enabled",NOT_WHITELISTED:"not_whitelisted",NOT_PERMITTED:"not_permitted",NOT_SUPPORTED:"not_supported",NOT_SUCCEEDED:"not_succeeded"},e=Registry.log,q=rea.FEATURES,g=Registry.get("promise"),l=Registry.get("helper"),f=Registry.get("permission"),r=Registry.get("i18n"),z=Registry.get("xmlhttprequest"),A=Registry.get("uri"),B=z.run,
h=d.OFF,t=[],k=null,u=!1,m={},v=!1,w=function(){var a=g();Registry.vendor(["vendor/saveas/filesaver"],function(){w=g.Pledge;a.resolve()});return a.promise()},n=function(){return null!==k?g.Pledge(k):f.has(f.permDownloads).then(function(a){k=a;e.debug("downs: permission to use rea.downloads ->",a);return n()})},C=function(a,b){if(this[a])this[a]("function"==typeof b?b():b)},p=function(a,b){this[a]&&(C.apply(this,arguments),this[a]=null)},E=function(a,b){k&&!v&&q.DOWNLOAD.SUPPORTED&&(rea.downloads.onChanged.addListener(D),
v=!0);var c={filename:a.name,body:a.data};["url","method","saveAs","headers"].forEach(function(b){c[b]=a[b]});rea.downloads.download(c,function(c){m[c]={callbacks:b,url:a.url,name:a.name}})},G=function(a,b){void 0===b&&(b={});var c=function(){return p.apply(b,arguments)};a.responseType="blob";a.method=a.method||"GET";B(a,{onload:function(b){if(4!=b.readyState||200!=b.status&&0!=b.status||b.error)c("onerror",{});else{var e=null;(b.responseHeaders?b.responseHeaders.split("\n"):[]).forEach(function(a){var b=
a.split(":");a=b.shift()||"";b=b.join(":")||"";"content-type"==a.trim().toLowerCase()&&(e=b.trim())});b=new Blob([b.response],{type:a.overrideMimeType||e||"binary/octet-stream"});saveAs(b,a.name);c("onload",{})}},ondone:function(){c("ondone",{})},onerror:b.onerror,ontimeout:b.ontimeout,onprogress:b.onprogress})},D=function(a){var b=m[a.id];if(b){var c=b.callbacks,f=function(){return p.apply(c,arguments)};a.error?(e.warn("downs: download of",b.name,"("+b.url+")","failed",a.error),f("onerror",{error:d.NOT_SUCCEEDED,
details:a.error})):a.endTime&&(e.debug("downs: download of",b.name,"("+b.url+")","finished"),f("onload",{}),f("ondone",{}),delete m[a.id])}},x=function(a){var b=!1;l.each(t,function(c,f){if(c&&c.length)try{var d;if("/"===c[0])c=c.replace(/^\//g,"").replace(/\/$/g,""),"$"!==c[c.length-1]&&(e.debug("downs: patching $ into",c),c+="$"),d=new RegExp(c,"i");else if("."===c[0]){var g=[l.escapeForRegExp(c),"$"].join("");d=new RegExp(g,"i")}else e.warn("downs: invalid file extension:",'"'+c+'"','starts neither with "." nor with "/"');
if(d&&-1!==a.search(d))return e.debug("downs:",c,"matched @",a),b=!0}catch(F){e.warn("downs: can't process",c,F)}});return b},y=function(){return f.has(f.permDownloads).then(function(a){var b=g();u||a?b.resolve({permission:a,asked:!1}):f.ask(f.permDownloads,r.getMessage("Browser_API_Downloads"),r.getMessage("Click_here_to_allow_TM_to_start_downloads")).done(function(a){b.resolve({permission:a,asked:!0})});u=!0;return b.promise()})};Registry.register("downloads","69",{start:function(a,
b){var c=this,f=arguments,g=function(){return p.apply(b,arguments)};e.debug("downs: start",a);if(h==d.OFF)e.warn("downs: feature is not enabled"),g("onerror",{error:d.NOT_ENABLED});else if(a.name&&x(a.name))if(h==d.CHROME)q.DOWNLOAD.SUPPORTED?n().done(function(a){a?E.apply(c,f):(e.warn("downs: download permission is missing"),g("onerror",{error:d.NOT_PERMITTED}))}):(e.warn("downs: this download mode is not supported"),g("onerror",{error:d.NOT_SUPPORTED}));else{var k=A.parse(a.url);a.name=a.name||
"File.download";w().done(function(){if("data:"==k.protocol){var b=saveAs,d,e=a.url;d=0<=e.split(",")[0].indexOf("base64")?window.atob(e.split(",")[1]):window.unescape(e.split(",")[1]);for(var e=e.split(",")[0].split(":")[1].split(";")[0],g=new Uint8Array(d.length),h=0;h<d.length;h++)g[h]=d.charCodeAt(h);d=new Blob([g],{type:e});b(d,a.name)}else G.apply(c,f)})}else e.warn("downs:",a.name,"is not whitelisted"),g("onerror",{error:d.NOT_WHITELISTED})},set_mode:function(a){h=a;h==d.CHROME&&n().done(function(a){a||
y().done(function(a){a.permission&&a.asked&&rea.page.reload()})})},set_whitelist:function(a){"Array"===l.toType(a)&&(t=a)},is_whitelisted:x,request_permission:y,remove_permission:function(){return f.remove(f.permDownloads)},staticVars:d})});
