Registry.require(["helper","convert"],function(){var p=Registry.get("helper"),q=Registry.get("convert"),v,r,y=function(a){var g=p.isLocalImage(a);return a&&"http"==a.substr(0,4)||g},z={"user-agent":!0,referer:!0,origin:!0,host:!0,"proxy-connection":!0,"accept-encoding":!0,"accept-charset":!0},C={"Cache-Control":"no-cache",Pragma:"no-cache"},t=function(a){return{responseXML:"",responseText:"",response:null,readyState:4,responseHeaders:"",status:0,statusText:"",error:a||"Forbidden"}},D=function(a,g,
m){void 0===m&&(m={});var d=p.assign({},g||{}),l=function(a,c){if(d[a])d[a]("function"==typeof c?c():c)};g=function(a,c){d[a]&&(l(a,c),d[a]=null)};if(m.internal||y(a.url)){var n=window.fetch&&a.url&&"http"==a.url.substr(0,4),b=!r&&a.anonymous,h=a.fetch;return n&&(b||h)?A(a,d,m,g,l):w(a,d,m,g,l)}console.warn("xhr: invalid scheme of url:",a.url);a=t("Invalid scheme");g("onerror",a);g("ondone",a)},B="TM-finalURL"+rea.runtime.short_id,A=function(a,g,m,d,l){var n=function(a){var f=[],b;a.headers&&(b=a.headers.get(B)||
a.url,a.headers.forEach(function(a,e){a.toLowerCase()!=B.toLowerCase()&&f.push(a+":"+e)}));return{readyState:4,responseHeaders:f.join("\n"),finalUrl:b,status:a.status,statusText:a.statusText}},b=function(b){(function(a,b){for(var c=[],e=0,k=a.length;e<k;e+=b)c.push(a.slice(e,b+e));return c})(b,parseInt(a.partialSize)).forEach(function(a){l("onpartial",{partial:a})})};try{var h={};h.method=a.method||"GET";h.redirect="follow";a.nocache&&(h.cache="no-store");h.credentials=a.anonymous?"omit":"include";
if(a.headers){var p={};Object.keys(a.headers).forEach(function(b){var d=b;z[b.toLowerCase()]&&(d=v+b);p[d]=a.headers[b]});h.headers=new window.Headers(p)}void 0!==a.data&&(h.body=a.binary?new Blob([q.str2arrbuf(a.data)]):"string"===typeof a.data?a.data:JSON.stringify(a.data));void 0!==a.timeout&&(h.timeout=a.timeout);window.fetch(a.url,h).then(function(c){var f=n(c);200!=f.status&&0!=f.status?0<a.retries?(a.retries--,A(a,g,m,d,l)):(d("onerror",f),d("ondone",f)):function(){var b;if(c.ok)void 0!==a.responseType?
function(){if(!a.convertBinary||"arraybuffer"!=a.responseType&&"blob"!=a.responseType){if("arraybuffer"==a.responseType)return c.arrayBuffer();if("blob"==a.responseType)return c.blob();console.warn("xhr: responseType",a.responseType," is not implemented!");return c.text()}return c.arrayBuffer().then(function(a){return q.arrbuf2str(a)})}().then(function(a){f.response=a;b()}):c.text().then(function(a){f.responseText=a;b()});else return f.responseXML=null,f.responseText="",f.response=null,{done:function(a){a()}};
return{done:function(a){b=a}}}().done(function(){if(a.partialSize&&g.onpartial){var c=a.convertBinary&&f.response?f.response:f.responseText;["response","responseText","responseXML"].forEach(function(a){delete f[a]});c&&(c.length>a.partialSize?b(c):f.response_data=c)}d("onload",f);d("ondone",f)})}).catch(function(a){a=n({status:408,statusText:a.message||"Request Timeout"});d("onerror",a);d("ondone",a)})}catch(c){console.error(c.stack),h=t(c.message),d("onerror",h),d("ondone",h)}return{abort:function(){}}},
w=function(a,g,m,d,l){var n,b=new XMLHttpRequest(a.anonymous?{mozAnon:!0}:{}),h=function(e){var k="",d=a.url;if(2<b.readyState&&(k=b.getAllResponseHeaders(),4==b.readyState)){k&&(k=k.replace(/TM-finalURL[0-9a-zA-Z]*\: .*[\r\n]{1,2}/,""));var c=b.getResponseHeader("TM-finalURL"+rea.runtime.short_id);c&&(d=c)}k={readyState:b.readyState,responseHeaders:k,finalUrl:d,status:4==b.readyState?b.status:0,statusText:4==b.readyState?b.statusText:""};e&&4==b.readyState?(b.responseType?(k.responseXML=null,k.responseText=
null,k.responseType=b.responseType):(k.responseXML=b.responseXML,k.responseText=b.responseText),k.response=b.response):(k.responseXML=null,k.responseText="",k.response=null);return k},r=function(e){(function(a,e){for(var b=[],d=0,c=a.length;d<c;d+=e)b.push(a.slice(d,e+d));return b})(e,parseInt(a.partialSize)).forEach(function(a){l("onpartial",{partial:a})})},c={onload:function(){var e=h(!0);4==e.readyState&&200!=e.status&&0!=e.status&&0<a.retries?(a.retries--,w(a,g,m,d,l)):function(){if(a.convertBinary&&
e.response){var b=e.responseType?e.responseType.toLowerCase():"";if("blob"==b){var d,c=new FileReader;c.onload=function(){e.response=q.arrbuf2str(c.result);d()};c.readAsArrayBuffer(e.response);return{done:function(a){d=a}}}"arraybuffer"==b?e.response=q.arrbuf2str(e.response):"json"==b&&(e.response=JSON.stringify(e.response))}return{done:function(a){a()}}}().done(function(){if(a.partialSize&&g.onpartial){var b=a.convertBinary&&e.response?e.response:e.responseText;["response","responseText","responseXML"].forEach(function(a){delete e[a]});
b&&(b.length>a.partialSize?r(b):e.response_data=b)}d("onload",e);4==e.readyState&&d("ondone",e)})},onerror:function(){var e=h();4==e.readyState&&200!=e.status&&0!=e.status&&0<a.retries?(a.retries--,w(a,g,m,d,l)):(d("onerror",e),d("ondone",e))},onloadstart:function(){l("onloadstart",function(){return h()})},onreadystatechange:function(){l("onreadystatechange",function(){return h()})},onprogress:function(a){l("onprogress",function(){var d=h(),c=d;void 0===c&&(c={});try{var f=null,g=null;if(a.lengthComputable||
0<a.total)f=a.loaded,g=a.total;else{var l=Number(p.getStringBetweenTags(d.responseHeaders.toLowerCase(),"content-length:","\n").trim()),m=2<d.readyState&&b.responseText?b.responseText.length:0;0==l&&(l=-1);f=a.loaded||m;g=a.total||l}c.lengthComputable=a.lengthComputable;c.loaded=f;c.done=f;c.position=f;c.total=g;c.totalSize=g}catch(n){}return c})},ontimeout:function(){var a=h();d("ontimeout");d("ondone",a)}},f=0==Object.keys(c).concat(["ondone"]).filter(function(a){return!!g[a]}).length;f||Object.keys(c).forEach(function(a){if(g[a]||
-1!=["ontimeout","onload","onerror"].indexOf(a))b[a]=c[a]});try{if(!m.internal&&!y(a.url))throw Error("Invalid scheme of url: "+a.url);b.open(a.method,a.url,!f,a.user,a.password);if(a.headers||a.nocache){var u={};a.headers&&p.assign(u,a.headers);a.nocache&&p.assign(u,C);Object.keys(u).forEach(function(a){var c=a;z[a.toLowerCase()]&&(c=v+a);b.setRequestHeader(c,u[a])})}void 0!==a.overrideMimeType&&b.overrideMimeType(a.overrideMimeType);void 0!==a.responseType&&(b.responseType=a.responseType);void 0!==
a.timeout&&(b.timeout=a.timeout);void 0!==a.data?a.binary?b.send(new Blob([q.str2arrbuf(a.data)])):b.send(a.data):b.send()}catch(e){console.error(e.stack);var x=t(e.message);d("onerror",x);d("ondone",x);f&&(n=x)}n=n||(f?h():{});return p.copy({abort:function(){b.abort()}},n)};Registry.register("xmlhttprequest","69",function(a,g){r=g;v=a;return{run:D,makeErrorResponse:t}})});
