"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var da,ea,ba,ga,ha,ia,ja,ka,la,ma,na,oa,pa;_.aa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global?window.global:this;da=function(){_.aa.Symbol||(_.aa.Symbol=ba);da=function(){}};ea=0;ba=function(a){return"jscomp_symbol_"+a+ea++};_.fa=function(){da();_.aa.Symbol.iterator||(_.aa.Symbol.iterator=_.aa.Symbol("iterator"));_.fa=function(){}};ga=function(){return{done:!0,value:void 0}};
ha=function(a,b){a instanceof String&&(a=String(a));var c=0;da();_.fa();var d={};da();_.fa();var e=(d.next=function(){if(c<a.length){var d=c++;return{value:b(d,a[d]),done:!1}}e.next=ga;return ga()},d[window.Symbol.iterator]=function(){return e},d);return e};ia=function(a,b){!Array.prototype[a]&&Object.defineProperties&&Object.defineProperty&&Object.defineProperty(Array.prototype,a,{configurable:!0,enumerable:!1,writable:!0,value:b})};
ja=function(a,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");};ka=function(a,b){if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");};la=function(a){ja(this,"repeat");var b=String(this);if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};
ma=function(a){ja(this,"codePointAt");var b=String(this),c=b.length;a=Number(a)||0;if(0<=a&&a<c){a|=0;var d=b.charCodeAt(a);if(55296>d||56319<d||a+1===c)return d;a=b.charCodeAt(a+1);return 56320>a||57343<a?d:1024*(d-55296)+a+9216}};na=function(a,b){b=void 0===b?0:b;ka(a,"includes");ja(this,"includes");return-1!==String(this).indexOf(a,b)};
oa=function(a,b){b=void 0===b?0:b;ka(a,"startsWith");ja(this,"startsWith");var c=String(this);a+="";for(var d=c.length,e=a.length,f=Math.max(0,Math.min(b|0,c.length)),h=0;h<e&&f<d;)if(c[f++]!=a[h++])return!1;return h>=e};pa=function(a,b){ka(a,"endsWith");ja(this,"endsWith");var c=String(this);a+="";void 0===b&&(b=c.length);for(var d=Math.max(0,Math.min(b|0,c.length)),e=a.length;0<e&&0<d;)if(c[--d]!=a[--e])return!1;return 0>=e};String.prototype.endsWith||(String.prototype.endsWith=pa);
String.prototype.startsWith||(String.prototype.startsWith=oa);String.prototype.includes||(String.prototype.includes=na);String.prototype.codePointAt||(String.prototype.codePointAt=ma);String.prototype.repeat||(String.prototype.repeat=la);ia("values",function(){return ha(this,function(a,b){return b})});ia("keys",function(){return ha(this,function(a){return a})});ia("entries",function(){return ha(this,function(a,b){return[a,b]})});_.qa=_.qa||{};_.l=this;_.ra="closure_uid_"+(1E9*Math.random()>>>0); _.m=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var sa,ta;_.p=function(a){return void 0!==a};sa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ta=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.ua=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.r=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Mc=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};
_.va=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.p(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.wa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.t=function(a,b,c){_.t=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ta:sa;return _.t.apply(null,arguments)};
_.xa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ya=function(a){return"function"==_.ua(a)};_.za=function(a){return"number"==typeof a};_.u=function(a){return"string"==typeof a};_.Aa=function(a){var b=_.ua(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Ba=function(a){return"array"==_.ua(a)};_.Ca=function(a){a.ua=function(){return a.nb?a.nb:a.nb=new a}};_.Da=function(){};
_.Ea=function(a){a=a.split(".");for(var b=_.l,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};_.Fa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Fa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.r(_.Fa,Error);_.Fa.prototype.name="CustomError";
var Ga;var Ja,La,Ma,Na,Oa,Pa,Qa,Ka,Sa,Va;_.Ha=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ia=function(a){return/^[\s\xa0]*$/.test(a)};Ja=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.Ra=function(a){if(!Ka.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(La,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ma,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Na,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Oa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Pa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Qa,"&#0;"));return a};La=/&/g;Ma=/</g;Na=/>/g;Oa=/"/g;Pa=/'/g;Qa=/\x00/g;Ka=/[\x00&<>"']/;Sa=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.Ta=function(a){return null==a?"":String(a)};_.Ua=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.Wa=function(a,b){for(var c=0,d=Ja(String(a)).split("."),e=Ja(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",n=e[h]||"",q=RegExp("(\\d*)(\\D*)","g"),G=RegExp("(\\d*)(\\D*)","g");do{var R=q.exec(k)||["","",""],Q=G.exec(n)||["","",""];if(0==R[0].length&&0==Q[0].length)break;c=Va(0==R[1].length?0:(0,window.parseInt)(R[1],10),0==Q[1].length?0:(0,window.parseInt)(Q[1],10))||Va(0==R[2].length,0==Q[2].length)||Va(R[2],Q[2])}while(0==c)}return c}; Va=function(a,b){return a<b?-1:a>b?1:0};
var Xa;Xa=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.u(a))return _.u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.v=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Ya=function(a,b){for(var c=_.u(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.Za=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.u(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e};
_.$a=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.u(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};_.ab=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.cb=function(a,b){var c=_.bb(a,b,void 0);return 0>c?null:_.u(a)?a.charAt(c):a[c]};
_.bb=function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.db=function(a,b){return 0<=Xa(a,b)};_.fb=function(a,b){var c=Xa(a,b),d;(d=0<=c)&&_.eb(a,c);return d};_.eb=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.gb=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};_.hb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
a:{var jb=_.l.navigator;if(jb){var kb=jb.userAgent;if(kb){_.ib=kb;break a}}_.ib=""}_.w=function(a){return-1!=_.ib.indexOf(a)};var mb,nb,ob,pb,rb;_.lb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};mb=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};nb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};ob=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};pb=function(a){return null!==a&&"withCredentials"in a};_.qb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};rb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "); _.sb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<rb.length;f++)c=rb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var tb=function(){return(_.w("Chrome")||_.w("CriOS"))&&!_.w("Edge")};var ub;ub=function(){return _.w("iPhone")&&!_.w("iPod")&&!_.w("iPad")};_.vb=function(){return _.w("Macintosh")};_.wb=function(){return _.w("Windows")};var xb,yb,Bb,Fb,Gb,Kb,Lb,Nb,Ob;xb=_.w("Opera");_.x=_.w("Trident")||_.w("MSIE");yb=_.w("Edge");_.zb=_.w("Gecko")&&!(-1!=_.ib.toLowerCase().indexOf("webkit")&&!_.w("Edge"))&&!(_.w("Trident")||_.w("MSIE"))&&!_.w("Edge");_.Ab=-1!=_.ib.toLowerCase().indexOf("webkit")&&!_.w("Edge");Bb=_.l.navigator||null;_.Cb=Bb&&Bb.platform||"";_.Db=_.vb();_.Eb=_.wb();Fb=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var Hb="",Ib=function(){var a=_.ib;if(_.zb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(yb)return/Edge\/([\d\.]+)/.exec(a);if(_.x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Ab)return/WebKit\/(\S+)/.exec(a);if(xb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ib&&(Hb=Ib?Ib[1]:"");if(_.x){var Jb=Fb();if(null!=Jb&&Jb>(0,window.parseFloat)(Hb)){Gb=String(Jb);break a}}Gb=Hb}Kb=Gb;Lb={};_.Mb=function(a){return Lb[a]||(Lb[a]=0<=_.Wa(Kb,a))};Nb=_.l.document; Ob=Nb&&_.x?Fb()||("CSS1Compat"==Nb.compatMode?(0,window.parseInt)(Kb,10):5):void 0;
var Pb=_.w("Firefox"),Qb=ub()||_.w("iPod"),Rb=_.w("iPad"),Sb=_.w("Android")&&!(tb()||_.w("Firefox")||_.w("Opera")||_.w("Silk")),Tb=tb(),Ub=_.w("Safari")&&!(tb()||_.w("Coast")||_.w("Opera")||_.w("Edge")||_.w("Silk")||_.w("Android"))&&!(ub()||_.w("iPad")||_.w("iPod"));
var Vb=null;var Wb,Yb,Xb,ac,bc,$b;Wb=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("c`"+a);};_.Zb=function(a,b){var c=[];Xb(new Yb(b),a,c);return c.join("")};Yb=function(a){this.a=a};
Xb=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.Ba(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],Xb(a,a.a?a.a.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),$b(d,c),c.push(":"),Xb(a,a.a?a.a.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":$b(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};ac={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};bc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g; $b=function(a,b){b.push('"',a.replace(bc,function(a){var b=ac[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),ac[a]=b);return b}),'"')};
var ec,hc;_.y=function(){};_.cc="function"==typeof window.Uint8Array;_.z=function(a,b,c,d){a.b=null;b||(b=c?[c]:[]);a.D=c?String(c):void 0;a.c=0===c?-1:0;a.H=b;a:{if(a.H.length&&(b=a.H.length-1,(c=a.H[b])&&"object"==typeof c&&!_.Ba(c))){a.h=b-a.c;a.g=c;break a}a.h=Number.MAX_VALUE}a.J={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.h?(c+=a.c,a.H[c]=a.H[c]||_.dc):a.g[c]=a.g[c]||_.dc};_.dc=[];_.A=function(a,b){if(b<a.h){var c=b+a.c,d=a.H[c];return d===_.dc?a.H[c]=[]:d}d=a.g[b];return d===_.dc?a.g[b]=[]:d};
_.B=function(a,b,c){b<a.h?a.H[b+a.c]=c:a.g[b]=c};_.C=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.A(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};_.D=function(a,b,c){a.b||(a.b={});var d=c?c.H:c;a.b[b]=c;_.B(a,b,d)};ec=_.l.JSON&&_.l.JSON.stringify||"object"===typeof JSON&&JSON.stringify;
_.y.prototype.j=_.cc?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!Vb){Vb={};for(var a=0;65>a;a++)Vb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}for(var a=Vb,b=[],e=0;e<this.length;e+=3){var f=this[e],h=e+1<this.length,k=h?this[e+1]:0,n=e+2<this.length,q=n?this[e+2]:0,G=f>>2,f=(f&3)<<4|k>>4,k=(k&15)<<2|q>>6,q=q&63;n||(q=64,h||(k=64));b.push(a[G],a[f],a[k],a[q])}return b.join("")};try{var b=ec.call(null,this.H,
fc)}finally{window.Uint8Array.prototype.toJSON=a}return b}:ec?function(){return ec.call(null,this.H,fc)}:function(){return _.Zb(this.H,fc)};var fc=function(a,b){if(_.za(b)){if((0,window.isNaN)(b))return"NaN";if(window.Infinity===b)return"Infinity";if(-window.Infinity===b)return"-Infinity"}return b};_.y.prototype.toString=function(){return this.H.toString()};hc=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)c[d]=0;for(d in b)c[d]=0;for(d in c)if(!_.gc(a[d],b[d]))return!1;return!0};
_.gc=function(a,b){if(a==b)return!0;if(!_.xa(a)||!_.xa(b)||a.constructor!=b.constructor)return!1;if(_.cc&&a.constructor===window.Uint8Array){if(a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!=b[c])return!1;return!0}if(a.constructor===Array){for(var d=void 0,e=void 0,f=Math.max(a.length,b.length),c=0;c<f;c++){var h=a[c],k=b[c];h&&h.constructor==Object&&(d=h,h=void 0);k&&k.constructor==Object&&(e=k,k=void 0);if(!_.gc(h,k))return!1}return d||e?(d=d||{},e=e||{},hc(d,e)):!0}if(a.constructor=== Object)return hc(a,b);throw Error("e");};
_.E=function(){this.O=this.O;this.A=this.A};_.E.prototype.O=!1;_.E.prototype.W=function(){this.O||(this.O=!0,this.B())};_.H=function(a,b){_.ic(a,_.wa(_.F,b))};_.ic=function(a,b,c){a.O?b.call(c):(a.A||(a.A=[]),a.A.push(_.p(c)?(0,_.t)(b,c):b))};_.E.prototype.B=function(){if(this.A)for(;this.A.length;)this.A.shift()()};_.F=function(a){a&&"function"==typeof a.W&&a.W()};
var jc=!_.x||9<=Number(Ob);!_.zb&&!_.x||_.x&&9<=Number(Ob)||_.zb&&_.Mb("1.9.1");_.x&&_.Mb("9");_.kc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.mc=function(){this.a="";this.g=_.lc;this.b=null};_.mc.prototype.Va=!0;_.mc.prototype.La=function(){return this.b};_.mc.prototype.Wa=!0;_.mc.prototype.Ua=function(){return this.a};_.lc={};_.nc=function(a,b){var c=new _.mc;c.a=a;c.b=b;return c};_.nc("<!DOCTYPE html>",0);_.nc("",0);_.oc=_.nc("<br>",0);
var uc,xc,wc;_.rc=function(a){return a?new _.pc(_.qc(a)):Ga||(Ga=new _.pc)};_.tc=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.sc(window.document,"*",a,b)[0];return d||null};
_.sc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.db(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.vc=function(a,b){_.lb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:uc.hasOwnProperty(d)?a.setAttribute(uc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};uc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
xc=function(a,b,c){function d(c){c&&b.appendChild(_.u(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.Aa(f)||_.xa(f)&&0<f.nodeType?d(f):(0,_.v)(wc(f)?_.hb(f):f,d)}};_.yc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.qc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};wc=function(a){if(a&&"number"==typeof a.length){if(_.xa(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ya(a))return"function"==typeof a.item}return!1};
_.pc=function(a){this.a=a||_.l.document||window.document};_.g=_.pc.prototype;_.g.sa=_.rc;_.g.ba=function(a){return _.u(a)?this.a.getElementById(a):a};
_.g.la=function(a,b,c){var d=this.a,e=arguments,f=e[0],h=e[1];if(!jc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',_.Ra(h.name),'"');if(h.type){f.push(' type="',_.Ra(h.type),'"');var k={};_.sb(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=d.createElement(f);h&&(_.u(h)?f.className=h:_.Ba(h)?f.className=h.join(" "):_.vc(f,h));2<e.length&&xc(d,f,e);return f};_.g.appendChild=function(a,b){a.appendChild(b)}; _.g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var zc="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""},Ac=function(){};Ac.prototype.next=function(){throw zc;};Ac.prototype.ja=function(){return this};
var Bc=function(a){if(a instanceof Ac)return a;if("function"==typeof a.ja)return a.ja(!1);if(_.Aa(a)){var b=0,c=new Ac;c.next=function(){for(;;){if(b>=a.length)throw zc;if(b in a)return a[b++];b++}};return c}throw Error("i");},Cc=function(a,b){if(_.Aa(a))try{(0,_.v)(a,b,void 0)}catch(c){if(c!==zc)throw c;}else{a=Bc(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==zc)throw c;}}},Dc=function(a){if(_.Aa(a))return _.hb(a);a=Bc(a);var b=[];Cc(a,function(a){b.push(a)});return b};
_.Ec=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.Ec?(c=a.V(),d=a.T()):(c=ob(a),d=nb(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.Ec.prototype.T=function(){Fc(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.Ec.prototype.V=function(){Fc(this);return this.a.concat()};_.Hc=function(a,b){return Gc(a.b,b)};
_.Ec.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.Ec.prototype.remove=function(a){return Gc(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&Fc(this),!0):!1};var Fc=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Gc(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Gc(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.g=_.Ec.prototype;
_.g.get=function(a,b){return Gc(this.b,a)?this.b[a]:b};_.g.set=function(a,b){Gc(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.g.forEach=function(a,b){for(var c=this.V(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.g.clone=function(){return new _.Ec(this)};_.g.ja=function(a){Fc(this);var b=0,c=this.c,d=this,e=new Ac;e.next=function(){if(c!=d.c)throw Error("j");if(b>=d.a.length)throw zc;var e=d.a[b++];return a?e:d.b[e]};return e}; var Gc=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Jc;_.Ic=function(a){if(a.T&&"function"==typeof a.T)return a.T();if(_.u(a))return a.split("");if(_.Aa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return nb(a)};
Jc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.Aa(a)||_.u(a))(0,_.v)(a,b,void 0);else{var c;if(a.V&&"function"==typeof a.V)c=a.V();else if(a.T&&"function"==typeof a.T)c=void 0;else if(_.Aa(a)||_.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=ob(a);for(var d=_.Ic(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
var Kc=function(a,b,c){this.c=c;this.g=a;this.h=b;this.b=0;this.a=null};Kc.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.g();return a};var Lc=function(a,b){a.h(b);a.b<a.c&&(a.b++,b.next=a.a,a.a=b)};var Pc;_.Mc=[];_.Nc=[];_.Oc=!1;Pc=function(a){_.Mc[_.Mc.length]=a;if(_.Oc)for(var b=0;b<_.Nc.length;b++)a((0,_.t)(_.Nc[b].b,_.Nc[b]))};var Qc,Sc,Tc,Rc;Qc=function(a){_.l.setTimeout(function(){throw a;},0)};_.Uc=function(a,b){var c=a;b&&(c=(0,_.t)(a,b));c=Rc(c);!_.ya(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.w("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Sc||(Sc=Tc()),Sc(c)):_.l.setImmediate(c)};
Tc=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.w("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.t)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.w("Trident")&&!_.w("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.p(c.next)){c=c.next;var a=c.jb;c.jb=null;a()}};return function(a){d.next={jb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};Rc=function(a){return a};Pc(function(a){Rc=a});
var Vc=function(){this.b=this.a=null},Xc=new Kc(function(){return new Wc},function(a){a.reset()},100);Vc.prototype.add=function(a,b){var c=Xc.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};Vc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Wc=function(){this.next=this.b=this.a=null};Wc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Wc.prototype.reset=function(){this.next=this.b=this.a=null};
var Yc,Zc,$c,ad,cd;_.bd=function(a,b){Yc||Zc();$c||(Yc(),$c=!0);ad.add(a,b)};Zc=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);Yc=function(){a.then(cd)}}else Yc=function(){_.Uc(cd)}};$c=!1;ad=new Vc;cd=function(){for(var a;a=ad.remove();){try{a.a.call(a.b)}catch(b){Qc(b)}Lc(Xc,a)}$c=!1};
var dd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},ed=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var gd,hd,id,fd,wd,sd,qd;_.I=function(a,b){this.a=0;this.l=void 0;this.c=this.b=this.g=null;this.h=this.A=!1;if(a!=_.Da)try{var c=this;a.call(b,function(a){fd(c,2,a)},function(a){fd(c,3,a)})}catch(d){fd(this,3,d)}};gd=function(){this.next=this.context=this.b=this.c=this.a=null;this.g=!1};gd.prototype.reset=function(){this.context=this.b=this.c=this.a=null;this.g=!1};hd=new Kc(function(){return new gd},function(a){a.reset()},100);id=function(a,b,c){var d=hd.get();d.c=a;d.b=b;d.context=c;return d};
_.jd=function(a){if(a instanceof _.I)return a;var b=new _.I(_.Da);fd(b,2,a);return b};_.ld=function(){var a,b=new _.I(function(b){a=b});return new kd(b,a)};_.I.prototype.then=function(a,b,c){return md(this,_.ya(a)?a:null,_.ya(b)?b:null,c)};dd(_.I);_.nd=function(a,b){return md(a,null,b,void 0)};_.I.prototype.j=function(a){0==this.a&&_.bd(function(){var b=new od(a);pd(this,b)},this)};
var pd=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?pd(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):qd(c),rd(c,e,3,b)))}a.g=null}else fd(a,3,b)},td=function(a,b){a.b||2!=a.a&&3!=a.a||sd(a);a.c?a.c.next=b:a.b=b;a.c=b},md=function(a,b,c,d){var e=id(null,null,null);e.a=new _.I(function(a,h){e.c=b?function(c){try{var e=b.call(d,c);a(e)}catch(q){h(q)}}:a;e.b=c?function(b){try{var e=
c.call(d,b);!_.p(e)&&b instanceof od?h(b):a(e)}catch(q){h(q)}}:h});e.a.g=a;td(a,e);return e.a};_.I.prototype.w=function(a){this.a=0;fd(this,2,a)};_.I.prototype.G=function(a){this.a=0;fd(this,3,a)};fd=function(a,b,c){0==a.a&&(a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.a=1,_.ud(c,a.w,a.G,a)||(a.l=c,a.a=b,a.g=null,sd(a),3!=b||c instanceof od||vd(a,c)))};
_.ud=function(a,b,c,d){if(a instanceof _.I)return td(a,id(b||_.Da,c||null,d)),!0;if(ed(a))return a.then(b,c,d),!0;if(_.xa(a))try{var e=a.then;if(_.ya(e))return wd(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};wd=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,k)}catch(n){k(n)}};sd=function(a){a.A||(a.A=!0,_.bd(a.v,a))};qd=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};
_.I.prototype.v=function(){for(var a;a=qd(this);)rd(this,a,this.a,this.l);this.A=!1};var rd=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,xd(b,c,d);else try{b.g?b.c.call(b.context):xd(b,c,d)}catch(e){yd.call(null,e)}Lc(hd,b)},xd=function(a,b,c){2==b?a.c.call(a.context,c):a.b&&a.b.call(a.context,c)},vd=function(a,b){a.h=!0;_.bd(function(){a.h&&yd.call(null,b)})},yd=Qc,od=function(a){_.Fa.call(this,a)};_.r(od,_.Fa);od.prototype.name="cancel"; var kd=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.zd=function(a,b){this.v=[];this.M=a;this.I=b||null;this.A=this.g=!1;this.c=void 0;this.J=this.N=this.G=!1;this.w=0;this.a=null;this.j=0};_.zd.prototype.l=function(a){if(this.g)this.c instanceof _.zd&&this.c.l();else{if(this.a){var b=this.a;delete this.a;a?b.l(a):(b.j--,0>=b.j&&b.l())}this.M?this.M.call(this.I,this):this.J=!0;this.g||this.K(new _.Ad)}};_.zd.prototype.D=function(a,b){this.G=!1;Bd(this,a,b)};
var Bd=function(a,b,c){a.g=!0;a.c=c;a.A=!b;Cd(a)},Ed=function(a){if(a.g){if(!a.J)throw new Dd;a.J=!1}};_.zd.prototype.b=function(a){Ed(this);Bd(this,!0,a)};_.zd.prototype.K=function(a){Ed(this);Bd(this,!1,a)};_.Gd=function(a,b,c){_.Fd(a,b,null,c)};_.Fd=function(a,b,c,d){a.v.push([b,c,d]);a.g&&Cd(a)};_.zd.prototype.then=function(a,b,c){var d,e,f=new _.I(function(a,b){d=a;e=b});_.Fd(this,d,function(a){a instanceof _.Ad?f.j():e(a)});return f.then(a,b,c)};dd(_.zd);
_.Hd=function(a,b){b instanceof _.zd?_.Gd(a,(0,_.t)(b.h,b)):_.Gd(a,function(){return b})};_.zd.prototype.h=function(a){var b=new _.zd;_.Fd(this,b.b,b.K,b);a&&(b.a=this,this.j++);return b};
var Id=function(a){return(0,_.ab)(a.v,function(a){return _.ya(a[1])})},Cd=function(a){if(a.w&&a.g&&Id(a)){var b=a.w,c=Jd[b];c&&(_.l.clearTimeout(c.R),delete Jd[b]);a.w=0}a.a&&(a.a.j--,delete a.a);for(var b=a.c,d=c=!1;a.v.length&&!a.G;){var e=a.v.shift(),f=e[0],h=e[1],e=e[2];if(f=a.A?h:f)try{var k=f.call(e||a.I,b);_.p(k)&&(a.A=a.A&&(k==b||k instanceof Error),a.c=b=k);if(ed(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.G=!0}catch(n){b=n,a.A=!0,Id(a)||(c=!0)}}a.c=b;d&&(k=(0,_.t)(a.D,
a,!0),d=(0,_.t)(a.D,a,!1),b instanceof _.zd?(_.Fd(b,k,d),b.N=!0):b.then(k,d));c&&(b=new Kd(b),Jd[b.R]=b,a.w=b.R)},Dd=function(){_.Fa.call(this)};_.r(Dd,_.Fa);Dd.prototype.message="Deferred has already fired";Dd.prototype.name="AlreadyCalledError";_.Ad=function(){_.Fa.call(this)};_.r(_.Ad,_.Fa);_.Ad.prototype.message="Deferred was canceled";_.Ad.prototype.name="CanceledError";var Kd=function(a){this.R=_.l.setTimeout((0,_.t)(this.b,this),0);this.a=a}; Kd.prototype.b=function(){delete Jd[this.R];throw this.a;};var Jd={};
var Ld=!_.x||9<=Number(Ob),Md=_.x&&!_.Mb("9");!_.Ab||_.Mb("528");_.zb&&_.Mb("1.9b")||_.x&&_.Mb("8")||xb&&_.Mb("9.5")||_.Ab&&_.Mb("528");_.zb&&!_.Mb("8")||_.x&&_.Mb("9");_.J=function(a,b){this.type="undefined"!=typeof _.Nd&&a instanceof _.Nd?String(a):a;this.g=this.target=b;this.c=!1;this.sb=!0};_.J.prototype.l=function(){this.c=!0};_.J.prototype.b=function(){this.sb=!1};var Od=function(a){Od[" "](a);return a};Od[" "]=_.Da;_.Pd=function(a,b){try{return Od(a[b]),!0}catch(c){}return!1};var Qd=function(a,b){_.J.call(this,a?a.type:"");this.g=this.target=null;this.keyCode=this.clientY=this.clientX=0;this.j=this.v=this.h=this.A=!1;this.a=this.state=null;if(a){this.type=a.type;var c=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;var d=a.relatedTarget;d&&_.zb&&_.Pd(d,"nodeName");null===c?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY):(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=
void 0!==c.clientY?c.clientY:c.pageY);this.keyCode=a.keyCode||0;this.A=a.ctrlKey;this.h=a.altKey;this.v=a.shiftKey;this.j=a.metaKey;this.state=a.state;this.a=a;a.defaultPrevented&&this.b()}};_.r(Qd,_.J);Qd.prototype.l=function(){Qd.C.l.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0}; Qd.prototype.b=function(){Qd.C.b.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Md)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Rd="closure_listenable_"+(1E6*Math.random()|0),Sd=function(a){return!(!a||!a[Rd])},Td=0;var Ud=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.ya=!!d;this.Na=e;this.key=++Td;this.removed=this.Ja=!1},Vd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Na=null};var Wd=function(a){this.src=a;this.a={};this.b=0};Wd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=Xd(a,b,d,e);-1<h?(b=a[h],c||(b.Ja=!1)):(b=new Ud(b,this.src,f,!!d,e),b.Ja=c,a.push(b));return b};Wd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Xd(e,b,c,d);return-1<b?(Vd(e[b]),_.eb(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Yd=function(a,b){var c=b.type;c in a.a&&_.fb(a.a[c],b)&&(Vd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Wd.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Vd(d[e]);delete this.a[c];this.b--}return b};
var Zd=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Xd(a,c,d,e));return-1<b?a[b]:null},$d=function(a){var b=_.p(void 0)?"undefined":void 0,c=_.p(b),d=c?b.toString():"",e=_.p(void 0);return mb(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].ya))return!0;return!1})},Xd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.ya==!!c&&f.Na==d)return e}return-1};
var ae,be,ce,fe,he,me,ie,oe,ne,je,ge,pe,ee;ae="closure_lm_"+(1E6*Math.random()|0);be={};ce=0;_.de=function(a,b,c,d,e){if(_.Ba(b)){for(var f=0;f<b.length;f++)_.de(a,b[f],c,d,e);return null}c=ee(c);return Sd(a)?a.listen(b,c,d,e):fe(a,b,c,!1,d,e)};
fe=function(a,b,c,d,e,f){if(!b)throw Error("k");var h=!!e,k=ge(a);k||(a[ae]=k=new Wd(a));c=k.add(b,c,d,e,f);if(c.proxy)return c;d=he();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(ie(b.toString()),d);else throw Error("l");ce++;return c};he=function(){var a=je,b=Ld?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.ke=function(a,b,c,d,e){if(_.Ba(b)){for(var f=0;f<b.length;f++)_.ke(a,b[f],c,d,e);return null}c=ee(c);return Sd(a)?a.Ma(b,c,d,e):fe(a,b,c,!0,d,e)};_.le=function(a,b,c,d,e){if(_.Ba(b))for(var f=0;f<b.length;f++)_.le(a,b[f],c,d,e);else c=ee(c),Sd(a)?a.wa(b,c,d,e):a&&(a=ge(a))&&(b=Zd(a,b,c,!!d,e))&&me(b)};
me=function(a){if(!_.za(a)&&a&&!a.removed){var b=a.src;if(Sd(b))Yd(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.ya):b.detachEvent&&b.detachEvent(ie(c),d);ce--;(c=ge(b))?(Yd(c,a),0==c.b&&(c.src=null,b[ae]=null)):Vd(a)}}};ie=function(a){return a in be?be[a]:be[a]="on"+a};oe=function(a,b,c,d){var e=!0;if(a=ge(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.ya==c&&!f.removed&&(f=ne(f,d),e=e&&!1!==f)}return e};
ne=function(a,b){var c=a.listener,d=a.Na||a.src;a.Ja&&me(a);return c.call(d,b)};
je=function(a,b){if(a.removed)return!0;if(!Ld){var c=b||_.Ea("window.event"),d=new Qd(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(n){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.g;f;f=f.parentNode)c.push(f);for(var f=a.type,h=c.length-1;!d.c&&0<=h;h--){d.g=c[h];var k=oe(c[h],f,!0,d),e=e&&k}for(h=0;!d.c&&h<c.length;h++)d.g=c[h],k=oe(c[h],f,!1,d),e=e&&k}return e}return ne(a,new Qd(b,this))}; ge=function(a){a=a[ae];return a instanceof Wd?a:null};pe="__closure_events_fn_"+(1E9*Math.random()>>>0);ee=function(a){if(_.ya(a))return a;a[pe]||(a[pe]=function(b){return a.handleEvent(b)});return a[pe]};Pc(function(a){je=a(je)});
_.K=function(){_.E.call(this);this.g=new Wd(this);this.ga=this;this.G=null};_.r(_.K,_.E);_.K.prototype[Rd]=!0;_.K.prototype.J=function(a){this.G=a};_.K.prototype.removeEventListener=function(a,b,c,d){_.le(this,a,b,c,d)};
_.L=function(a,b){var c,d=a.G;if(d)for(c=[];d;d=d.G)c.push(d);var d=a.ga,e=b,f=e.type||e;if(_.u(e))e=new _.J(e,d);else if(e instanceof _.J)e.target=e.target||d;else{var h=e,e=new _.J(f,d);_.sb(e,h)}var h=!0,k;if(c)for(var n=c.length-1;!e.c&&0<=n;n--)k=e.g=c[n],h=k.X(f,!0,e)&&h;e.c||(k=e.g=d,h=k.X(f,!0,e)&&h,e.c||(h=k.X(f,!1,e)&&h));if(c)for(n=0;!e.c&&n<c.length;n++)k=e.g=c[n],h=k.X(f,!1,e)&&h;return h};_.g=_.K.prototype;_.g.B=function(){_.K.C.B.call(this);this.g&&this.g.removeAll(void 0);this.G=null};
_.g.listen=function(a,b,c,d){return this.g.add(String(a),b,!1,c,d)};_.g.Ma=function(a,b,c,d){return this.g.add(String(a),b,!0,c,d)};_.g.wa=function(a,b,c,d){return this.g.remove(String(a),b,c,d)};_.g.X=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.ya==b){var h=f.listener,k=f.Na||f.src;f.Ja&&Yd(this.g,f);d=!1!==h.call(k,c)&&d}}return d&&0!=c.sb};
var qe=function(){};qe.prototype.a=null;var se=function(a){var b;(b=a.a)||(b={},re(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var te,ue=function(){};_.r(ue,qe);var ve=function(a){return(a=re(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},re=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("m");}return a.b};te=new ue;
_.we=function(a,b){_.K.call(this);this.h=a||1;this.c=b||_.l;this.j=(0,_.t)(this.v,this);this.l=(0,_.m)()};_.r(_.we,_.K);_.we.prototype.b=!1;_.we.prototype.a=null;_.we.prototype.setInterval=function(a){this.h=a;this.a&&this.b?(this.stop(),_.xe(this)):this.a&&this.stop()};
_.we.prototype.v=function(){if(this.b){var a=(0,_.m)()-this.l;0<a&&a<.8*this.h?this.a=this.c.setTimeout(this.j,this.h-a):(this.a&&(this.c.clearTimeout(this.a),this.a=null),_.L(this,"tick"),this.b&&(this.a=this.c.setTimeout(this.j,this.h),this.l=(0,_.m)()))}};_.xe=function(a){a.b=!0;a.a||(a.a=a.c.setTimeout(a.j,a.h),a.l=(0,_.m)())};_.we.prototype.stop=function(){this.b=!1;this.a&&(this.c.clearTimeout(this.a),this.a=null)};_.we.prototype.B=function(){_.we.C.B.call(this);this.stop();delete this.c}; _.ye=function(a,b,c){if(_.ya(a))c&&(a=(0,_.t)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.t)(a.handleEvent,a);else throw Error("n");return 2147483647<Number(b)?-1:_.l.setTimeout(a,b||0)};_.ze=function(a){_.l.clearTimeout(a)};
var Ae=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Be=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f,h=null;0<=e?(f=c[d].substring(0,e),h=c[d].substring(e+1)):f=c[d];b(f,h?(0,window.decodeURIComponent)(h.replace(/\+/g," ")):"")}};
var Ce=function(a){_.K.call(this);this.na=new _.Ec;this.I=a||null;this.b=!1;this.D=this.a=null;this.N="";this.j=0;this.h="";this.c=this.M=this.v=this.K=!1;this.l=0;this.w=null;this.$="";this.U=this.ca=!1},De,Ee,Ne,Le,Je,Oe,Pe;_.r(Ce,_.K);De=/^https?$/i;Ee=["POST","PUT"];_.Fe=[];_.Ge=function(a,b,c,d,e,f,h){var k=new Ce;_.Fe.push(k);b&&k.listen("complete",b);k.Ma("ready",k.ia);f&&(k.l=Math.max(0,f));h&&(k.ca=h);k.send(a,c,d,e)};Ce.prototype.ia=function(){this.W();_.fb(_.Fe,this)};
Ce.prototype.send=function(a,b,c,d){if(this.a)throw Error("p`"+this.N+"`"+a);b=b?b.toUpperCase():"GET";this.N=a;this.h="";this.j=0;this.K=!1;this.b=!0;this.a=this.I?ve(this.I):ve(te);this.D=this.I?se(this.I):se(te);this.a.onreadystatechange=(0,_.t)(this.Z,this);try{this.M=!0,this.a.open(b,String(a),!0),this.M=!1}catch(f){He(this,f);return}a=c||"";var e=this.na.clone();d&&Jc(d,function(a,b){e.set(b,a)});d=_.cb(e.V(),Ie);c=_.l.FormData&&a instanceof _.l.FormData;!_.db(Ee,b)||d||c||e.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.$&&(this.a.responseType=this.$);pb(this.a)&&(this.a.withCredentials=this.ca);try{Je(this),0<this.l&&((this.U=Ke(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.t)(this.Y,this)):this.w=_.ye(this.Y,this.l,this)),this.v=!0,this.a.send(a),this.v=!1}catch(f){He(this,f)}};
var Ke=function(a){return _.x&&_.Mb(9)&&_.za(a.timeout)&&_.p(a.ontimeout)},Ie=function(a){return"content-type"==a.toLowerCase()};Ce.prototype.Y=function(){"undefined"!=typeof _.qa&&this.a&&(this.h="Timed out after "+this.l+"ms, aborting",this.j=8,_.L(this,"timeout"),this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,this.j=8,_.L(this,"complete"),_.L(this,"abort"),Le(this)))};
var He=function(a,b){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.h=b;a.j=5;Me(a);Le(a)},Me=function(a){a.K||(a.K=!0,_.L(a,"complete"),_.L(a,"error"))};Ce.prototype.B=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Le(this,!0));Ce.C.B.call(this)};Ce.prototype.Z=function(){this.O||(this.M||this.v||this.c?Ne(this):this.S())};Ce.prototype.S=function(){Ne(this)};
Ne=function(a){if(a.b&&"undefined"!=typeof _.qa&&(!a.D[1]||4!=Oe(a)||2!=Pe(a)))if(a.v&&4==Oe(a))_.ye(a.Z,0,a);else if(_.L(a,"readystatechange"),4==Oe(a)){a.b=!1;try{if(_.Qe(a))_.L(a,"complete"),_.L(a,"success");else{a.j=6;var b;try{b=2<Oe(a)?a.a.statusText:""}catch(c){b=""}a.h=b+" ["+Pe(a)+"]";Me(a)}}finally{Le(a)}}};Le=function(a,b){if(a.a){Je(a);var c=a.a,d=a.D[0]?_.Da:null;a.a=null;a.D=null;b||_.L(a,"ready");try{c.onreadystatechange=d}catch(e){}}};
Je=function(a){a.a&&a.U&&(a.a.ontimeout=null);_.za(a.w)&&(_.ze(a.w),a.w=null)};_.Qe=function(a){var b=Pe(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.N).match(Ae)[1]||null,!a&&_.l.self&&_.l.self.location&&(a=_.l.self.location.protocol,a=a.substr(0,a.length-1)),b=!De.test(a?a.toLowerCase():"");c=b}return c};Oe=function(a){return a.a?a.a.readyState:0};Pe=function(a){try{return 2<Oe(a)?a.a.status:-1}catch(b){return-1}}; _.Re=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};Pc(function(a){Ce.prototype.S=a(Ce.prototype.S)});
var Te;_.M=function(a){_.E.call(this);this.G=a;this.h={}};_.r(_.M,_.E);var Se=[];_.M.prototype.listen=function(a,b,c,d){_.Ba(b)||(b&&(Se[0]=b.toString()),b=Se);for(var e=0;e<b.length;e++){var f=_.de(a,b[e],c||this.handleEvent,d||!1,this.G||this);if(!f)break;this.h[f.key]=f}return this};_.We=function(a,b,c,d){Te(a,b,c,d,void 0)};Te=function(a,b,c,d,e,f){if(_.Ba(c))for(var h=0;h<c.length;h++)Te(a,b,c[h],d,e,f);else(b=_.ke(b,c,d||a.handleEvent,e,f||a.G||a))&&(a.h[b.key]=b)};
_.M.prototype.wa=function(a,b,c,d,e){if(_.Ba(b))for(var f=0;f<b.length;f++)this.wa(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.G||this,c=ee(c),d=!!d,b=Sd(a)?Zd(a.g,String(b),c,d,e):a?(a=ge(a))?Zd(a,b,c,d,e):null:null,b&&(me(b),delete this.h[b.key]);return this};_.M.prototype.removeAll=function(){_.lb(this.h,function(a,b){this.h.hasOwnProperty(b)&&me(a)},this);this.h={}};_.M.prototype.B=function(){_.M.C.B.call(this);this.removeAll()};_.M.prototype.handleEvent=function(){throw Error("q");};
var Xe=function(){};Xe.prototype.c=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var Ye=function(a){(a?a:function(){}).Lb=!0};_.Ze=function(){};_.r(_.Ze,Xe);_.Ze.prototype.b=function(a){return a};Ye(_.Ze.prototype.b);_.Ze.prototype.g=function(){return!0};Ye(_.Ze.prototype.g);var $e=function(a){_.z(this,a,0,null)};_.r($e,_.y);var af;af=function(a,b){var c=new $e;_.B(c,1,b);_.B(c,2,a);return c};_.bf=af("?",0);_.cf=af("q",1);_.df=af("<",2);_.ef=af(">",3);_.ff=af("~",4);_.gf=af("s",5);_.N=function(a,b,c){this.g=a;this.b=b||null;this.a=c||[]};_.N.prototype.toString=function(){return this.g};var hf,jf,kf,mf,of,xf,pf,rf,qf,uf,sf,nf,yf;_.O=function(a,b){this.b=this.j=this.h="";this.c=null;this.l=this.a="";this.A=!1;var c;a instanceof _.O?(this.A=_.p(b)?b:a.A,hf(this,a.h),this.j=a.j,this.b=a.b,jf(this,a.c),this.a=a.a,kf(this,a.g.clone()),_.lf(this,a.l)):a&&(c=String(a).match(Ae))?(this.A=!!b,hf(this,c[1]||"",!0),this.j=mf(c[2]||""),this.b=mf(c[3]||"",!0),jf(this,c[4]),this.a=mf(c[5]||"",!0),kf(this,c[6]||"",!0),_.lf(this,c[7]||"",!0)):(this.A=!!b,this.g=new nf(null,0,this.A))};
_.O.prototype.toString=function(){var a=[],b=this.h;b&&a.push(of(b,pf,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(of(b,pf,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(of(c,"/"==c.charAt(0)?qf:rf,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",of(c,sf));return a.join("")};_.O.prototype.clone=function(){return new _.O(this)};
hf=function(a,b,c){a.h=c?mf(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};jf=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("t`"+b);a.c=b}else a.c=null};kf=function(a,b,c){b instanceof nf?(a.g=b,tf(a.g,a.A)):(c||(b=of(b,uf)),a.g=new nf(b,0,a.A))};_.P=function(a,b,c){a.g.set(b,c)};_.lf=function(a,b,c){a.l=c?mf(b):b};_.vf=function(a){return a instanceof _.O?a.clone():new _.O(a,void 0)};
_.wf=function(a,b){a instanceof _.O||(a=_.vf(a));b instanceof _.O||(b=_.vf(b));var c=a,d=b,e=c.clone(),f=!!d.h;f?hf(e,d.h):f=!!d.j;f?e.j=d.j:f=!!d.b;f?e.b=d.b:f=null!=d.c;var h=d.a;if(f)jf(e,d.c);else if(f=!!d.a)if("/"!=h.charAt(0)&&(c.b&&!c.a?h="/"+h:(c=e.a.lastIndexOf("/"),-1!=c&&(h=e.a.substr(0,c+1)+h))),c=h,".."==c||"."==c)h="";else if(-1!=c.indexOf("./")||-1!=c.indexOf("/.")){for(var h=0==c.lastIndexOf("/",0),c=c.split("/"),k=[],n=0;n<c.length;){var q=c[n++];"."==q?h&&n==c.length&&k.push(""):
".."==q?((1<k.length||1==k.length&&""!=k[0])&&k.pop(),h&&n==c.length&&k.push("")):(k.push(q),h=!0)}h=k.join("/")}else h=c;f?e.a=h:f=""!==d.g.toString();f?kf(e,mf(d.g.toString())):f=!!d.l;f&&_.lf(e,d.l);return e};mf=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};of=function(a,b,c){return _.u(a)?(a=(0,window.encodeURI)(a).replace(b,xf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};
xf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};pf=/[#\/\?@]/g;rf=/[\#\?:]/g;qf=/[\#\?]/g;uf=/[\#\?@]/g;sf=/#/g;nf=function(a,b,c){this.b=this.a=null;this.g=a||null;this.c=!!c};yf=function(a){a.a||(a.a=new _.Ec,a.b=0,a.g&&Be(a.g,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};nf.prototype.add=function(a,b){yf(this);this.g=null;a=zf(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b=this.b+1;return this};
nf.prototype.remove=function(a){yf(this);a=zf(this,a);return _.Hc(this.a,a)?(this.g=null,this.b=this.b-this.a.get(a).length,this.a.remove(a)):!1};nf.prototype.clear=function(){this.a=this.g=null;this.b=0};var Af=function(a,b){yf(a);b=zf(a,b);return _.Hc(a.a,b)};nf.prototype.V=function(){yf(this);for(var a=this.a.T(),b=this.a.V(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
nf.prototype.T=function(a){yf(this);var b=[];if(_.u(a))Af(this,a)&&(b=_.gb(b,this.a.get(zf(this,a))));else{a=this.a.T();for(var c=0;c<a.length;c++)b=_.gb(b,a[c])}return b};nf.prototype.set=function(a,b){yf(this);this.g=null;a=zf(this,a);Af(this,a)&&(this.b=this.b-this.a.get(a).length);this.a.set(a,[b]);this.b=this.b+1;return this};nf.prototype.get=function(a,b){var c=a?this.T(a):[];return 0<c.length?String(c[0]):b};
_.Bf=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(zf(a,b),_.hb(c)),a.b=a.b+c.length)};nf.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.V(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.T(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}return this.g=a.join("&")};
nf.prototype.clone=function(){var a=new nf;a.g=this.g;this.a&&(a.a=this.a.clone(),a.b=this.b);return a};var zf=function(a,b){var c=String(b);a.c&&(c=c.toLowerCase());return c},tf=function(a,b){b&&!a.c&&(yf(a),a.g=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Bf(this,e,a))},a));a.c=b};
_.Ze.C||_.r(_.Ze,Xe);_.Cf=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}};
_.Df=function(a){_.z(this,a,"uv_i_sc",null)};_.r(_.Df,_.y);_.Df.messageId="uv_i_sc";_.Ef=function(a){_.z(this,a,"uv_qm",null)};_.r(_.Ef,_.y);_.Ef.messageId="uv_qm";_.Ff=function(a){_.z(this,a,"uv_r_rr",null)};_.r(_.Ff,_.y);_.Ff.messageId="uv_r_rr";_.Gf=function(a){_.z(this,a,"uv_r_frm",null)};_.r(_.Gf,_.y);_.Gf.messageId="uv_r_frm";_.Hf=function(a){_.z(this,a,0,null)};_.r(_.Hf,_.y);
var Jf=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("v");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,k,n,q,G,R){if("%"==q)return"%";var Q=c.shift();if("undefined"==typeof Q)throw Error("w");arguments[0]=Q;return If[q].apply(null,arguments)})},If={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Sa(" ",Number(c)-a.length):Sa(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Sa(" ",a):f+Sa(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,k){return If.f((0,window.parseInt)(a,10),b, c,d,0,f,h,k)}};If.i=If.d;If.u=If.d;
_.S=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Jf("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString()+Jf(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Jf.apply({},c)))};
_.Kf=new _.N("pVbxBc");_.Lf=new _.N("S53Hlb");_.Mf=new _.N("Eyr1Zc");_.T=new _.N("nED8Yb");_.Nf=new _.N("xclgJb");_.Of=new _.N("Qz9Lj");_.Qf=function(a){_.z(this,a,"h_cd",Pf)};_.r(_.Qf,_.y);var Pf=[1,4,5];_.Qf.messageId="h_cd";_.Rf=function(a){_.z(this,a,"h_icr",null)};_.r(_.Rf,_.y);_.Rf.messageId="h_icr";_.Rf.prototype.a=function(){return _.A(this,1)};_.Sf=function(a){_.z(this,a,"h_opc",null)};_.r(_.Sf,_.y);_.Sf.messageId="h_opc";_.Tf=function(a){_.z(this,a,"h_sc",null)};_.r(_.Tf,_.y);_.Tf.messageId="h_sc";_.Uf=function(a){_.z(this,a,"h_po",null)};_.r(_.Uf,_.y);_.Uf.messageId="h_po";_.Vf=function(a){return _.wf(a,"/webchat/host-js")};_.Wf=function(a){var b=_.Vf(_.A(a,2));_.P(b,"prop",_.Cf(27));_.P(b,"b",1);_.P(b,"hl",_.A(a,3));_.A(a,4)&&_.P(b,"jsmode",_.A(a,4));_.P(b,"zx",_.Ua());return b.toString()};_.Xf=function(a){_.z(this,a,"h_ssf",null)};_.r(_.Xf,_.y);_.Xf.messageId="h_ssf";_.Zf=function(a){_.z(this,a,"h_exts",Yf)};_.r(_.Zf,_.y);var Yf=[2];_.Zf.messageId="h_exts";var $f=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};$f.prototype.setVersion=function(a){this.c=a;return this};$f.prototype.Ba=function(a){this.a=a;return this};$f.prototype.Ya=function(a){this.g=_.qb(a);return this};var ag=function(){};var bg=function(){};_.r(bg,ag);bg.prototype.clear=function(){var a=Dc(this.ja(!0)),b=this;(0,_.v)(a,function(a){b.remove(a)})};var cg=function(a){this.a=a};_.r(cg,bg);_.g=cg.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.u(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ja=function(a){var b=0,c=this.a,d=new Ac;d.next=function(){if(b>=c.length)throw zc;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.u(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var dg=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.r(dg,cg);var fg=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new dg);if(null!=this.b&&this.b.isAvailable()){var c=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate");if(null!=c)try{this.a=Wb(c)||[]}catch(d){}}c=!1;_.Ba(this.a)||(this.a=[],c=!0);for(;this.a.length>this.g;)this.a.shift(),c=!0;c&&eg(this)},eg=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Zb(a.a))}catch(b){}};
_.gg=function(a){_.E.call(this);this.a=a;this.h=!1};_.r(_.gg,_.E);_.gg.prototype.setEnabled=function(a){this.h=a};var hg=function(a){return(a=a.exec(_.ib))?a[1]:""},ig=function(){if(Pb)return hg(/Firefox\/([0-9.]+)/);if(_.x||yb||xb)return Kb;if(Tb)return hg(/Chrome\/([0-9.]+)/);if(Ub&&!(ub()||_.w("iPad")||_.w("iPod")))return hg(/Version\/([0-9.]+)/);if(Qb||Rb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.ib);if(a)return a[1]+"."+a[2]}else if(Sb)return(a=hg(/Android\s+([0-9.]+)/))?a:hg(/Version\/([0-9.]+)/);return""}();
var U=function(a){_.gg.call(this,a);this.w=100;this.v={};this.P=null;this.g="";this.G=!0;this.j=10;this.b=null;this.c=!1};_.r(U,_.gg);U.prototype.xb=function(a){this.G=a;return this};U.prototype.setUseLocalStorage=U.prototype.xb;U.prototype.zc=function(a){this.j=Math.min(a,100);return this};U.prototype.setMaxErrorsPerHour=U.prototype.zc;U.prototype.vb=function(a){this.w=a;return this};U.prototype.setGlobalSampling=U.prototype.vb;U.prototype.hb=function(a,b){this.v[a]=b;return this};
U.prototype.addPerErrorMessageSampling=U.prototype.hb;U.prototype.ub=function(a){this.P=a;return this};U.prototype.setCallback=U.prototype.ub;U.prototype.yc=function(a){this.g=a;return this};U.prototype.setClientId=U.prototype.yc;U.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.D.bind(this);this.setEnabled(!0);return!0};U.prototype.enable=U.prototype.enable;
U.prototype.qb=function(a,b,c,d,e){var f=_.vf(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ya(this.P)||this.P(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.v);for(var k=100,n=0;n<h.length;++n){var q=h[n];(new RegExp(q)).test(a)&&(k=this.v[q])}if(h=(100*Math.random()).toFixed(6)>=this.w*k/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new fg(this.j,this.G));if(null===this.b)h=0;else{a:{h=this.b;k=(0,_.m)();if(h.a.length==h.g)if(h.a[0]<k-36E5)h.a.shift();else{h=!1;break a}h.a.push(k);
eg(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.qb(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,k="Other",xb?k="Opera":_.x?k="Internet Explorer":Pb?k="Firefox":Tb?k="Chrome":Ub&&(k="Safari"),h.browser=k,h.browser_version=ig,h.os=_.w("CrOS")?"Chrome OS":_.w("Linux")?"Linux":_.wb()?"Windows":_.w("Android")?"Android":ub()?"iPhone":_.w("iPad")?"iPad":_.w("iPod")?"iPod":_.vb()?"Mac":"Unknown",k=_.ib,n="",_.wb()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(k=n.exec(k))?k[1]:"0.0"):ub()||_.w("iPad")||
_.w("iPod")?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,n=(k=n.exec(k))&&k[1].replace(/_/g,".")):_.vb()?(n=/Mac OS X ([0-9_.]+)/,n=(k=n.exec(k))?k[1].replace(/_/g,"."):"10"):_.w("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(k=n.exec(k))&&k[1]):_.w("CrOS")&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(k=n.exec(k))&&k[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.Ia(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,b=
jg(h),e=null!=e?_.Ta(e.stack):"",_.Ia(a)||(c=e.split("\n"),-1<c[0].indexOf(a)&&(c.splice(0,1),e=c.join("\n"))),kg(this,"https://clients2.google.com/cr/staging_report",b,e),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Ta(this.a.a),_.Ia(a)||(f.version=a),kg(this,"https://clients2.google.com/cr/staging_perf",jg(f)))};U.prototype.reportError=U.prototype.qb;U.prototype.D=function(a,b,c,d,e){this.qb(a,b,c,d,e);null!=this.l&&_.ya(this.l)&&this.l(a,b,c,d,e)};
var jg=function(a){var b="",c;for(c in a)b+=_.Ia(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},kg=function(a,b,c,d){d=d||"";var e=_.Ia(d)?{}:{"Content-Type":"text/plain"};_.Ge(b+c,a.J.bind(a,b),"POST",d,e,6E4,!0)};U.prototype.J=function(a,b){_.Qe(b.target)};
var lg=function(a){_.E.call(this);this.b=new $f(a);this.a={}};_.r(lg,_.E);_.va("webmonitoring.Monitoring",lg);lg.prototype.setVersion=function(a){this.b.setVersion(a);return this};lg.prototype.setVersion=lg.prototype.setVersion;lg.prototype.Ba=function(a){this.b.Ba(a);return this};lg.prototype.setChannel=lg.prototype.Ba;lg.prototype.Ya=function(a){this.b.Ya(a);return this};lg.prototype.setContext=lg.prototype.Ya;lg.prototype.Ka=function(){null!=this.a[2]||(this.a[2]=new U(this.b));return this.a[2]}; lg.prototype.createJsErrorsReporter=lg.prototype.Ka;
var mg=function(a){lg.call(this,a)};_.r(mg,lg);mg.prototype.setVersion=function(a){return mg.C.setVersion.call(this,a)};mg.prototype.Ba=function(a){return mg.C.Ba.call(this,a)};mg.prototype.Ka=function(){var a=mg.C.Ka.call(this);a.c=!0;return a};_.ng=function(){lg.call(this,"ultraviolet");this.setVersion(window.chrome.runtime.id)};_.r(_.ng,mg);_.Ca(_.ng);_.og=function(){_.ng.ua().Ka().xb(!1).vb(100).hb("Script error.",0).enable()};_.ng.ua();_.pg=function(a,b){this.l=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.g=this.A=null;this.j=b||"u";this.a=this.h=null;this.b=[]};_.pg.prototype.message=function(){var a={};a.i=this.a;a.m=this.b;a.r=this.j;a.o=this.h;a.s=this.g;a.st=this.c;a.d=this.A;a.dt=this.l;return a};_.pg.prototype.message=_.pg.prototype.message;
_.qg=function(a,b){var c={};try{c=JSON.parse(b)||{}}catch(e){}for(var d in c)switch(d){case "r":a.j=c[d];break;case "i":a.a=c[d];break;case "m":a.b=c[d];break;case "o":a.h=c[d];break;case "s":a.g=c[d];break;case "d":a.A=c[d];break;case "st":a.c=c[d];break;case "dt":a.l=c[d]}};_.pg.prototype.source=function(){return this.g};_.pg.prototype.target=function(){return this.A};_.pg.prototype.content=function(){return this.b};
var rg=function(a,b){_.J.call(this,a,b);this.L=b};_.r(rg,_.J);var sg=function(a){_.z(this,a,"capi_md1571",null)};_.r(sg,_.y);sg.messageId="capi_md1571";var tg={eb:0,Fc:1,Ec:2,cb:3,Pa:4},ug=function(a){_.z(this,a,0,null)};_.r(ug,_.y);var wg=function(){for(var a=10,b=vg,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},vg="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.xg=function(a,b){_.E.call(this);this.j=b||wg();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.M(this);_.H(this,this.h);this.h.listen(window,"message",this.v)};_.r(_.xg,_.E);_.xg.prototype.ha=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.xg.prototype.v=function(a){a=a.a;var b;b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.O(b)).b,b=_.Ha(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.u(b)&&"["==b[0]){var c;try{if(c=JSON.parse(b),!_.Ba(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new sg(c),_.A(c,1)==this.j)){b=_.A(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.ha(a.origin,a.source);
1==_.A(c,2)?this.send(2):this.l(c,a)}}};_.xg.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new sg;_.B(b,3,this.j);_.B(b,1,this.a);_.B(b,2,a);var d=JSON.stringify(b.H),e=this.g,f=this.c;_.x?_.ye(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var yg=function(a,b,c,d,e){this.g=_.ld();this.a=new _.xg((0,_.t)(this.h,this),d);this.a.ha(a,b,e);this.a.a=c;this.b=new _.we(50);_.xe(this.b);_.de(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.A;b=id(b,b,this);b.g=!0;td(a,b)};yg.prototype.A=function(){_.F(this.a);_.le(this.b,"tick",this.c,!1,this);_.F(this.b)};yg.prototype.c=function(){this.a.send(1)};yg.prototype.h=function(a,b){2==_.A(a,2)&&this.g.b(b.origin)};
var zg=function(a,b,c){_.E.call(this);this.b=a;a=_.A(b,3);b=_.A(b,1);this.a=new _.xg((0,_.t)(this.g,this),b);this.a.a=a;c&&this.a.ha(c.origin,c.source);_.H(this,this.a)};_.r(zg,_.E);zg.prototype.send=function(a){var b=new sg;_.D(b,4,a);this.a.send(tg.eb,b)};zg.prototype.connect=function(a,b){this.a.ha(a,b);this.a.send(tg.cb)};zg.prototype.g=function(a){_.A(a,2)==tg.eb&&(a=_.C(a,ug,4),this.b(a))};zg.prototype.c=_.Da;
var Bg=function(a,b,c){_.E.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],Ag(this)):(this.a=new _.xg(_.Da,_.A(b,1)),a=_.A(b,3),this.a.a=a)};_.r(Bg,_.E);Bg.prototype.B=function(){Bg.C.B.call(this);this.b&&this.b.close();_.F(this.a)};Bg.prototype.c=function(){this.g=new _.M(this);_.H(this,this.g);Ag(this)};Bg.prototype.send=function(a){this.b.postMessage(a.H)};
Bg.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;Ag(this);var d=this.a;this.a=null;c=c.port2;d.ha(a,b);d.send(tg.Pa,void 0,[c]);_.F(d)};var Ag=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};Bg.prototype.j=function(a){a=a.a;var b;try{b=new ug(a.data)}catch(c){return}this.h(b)};
var Cg=function(a,b,c){var d=!1;_.p(_.A(b,2))?_.A(b,2)==tg.Pa&&(d=!0):d=Tb;return d?new Bg(a,b,c):new zg(a,b,c)};var Gg;_.Dg=function(){_.K.call(this);this.h=null;this.l=!1;this.j=[];this.c=[];_.ic(this,this.w,this);this.b=null};_.r(_.Dg,_.K);_.Dg.prototype.w=function(){for(;this.c.length;)this.c.shift()()};_.Fg=function(a){a.w();a.j=[];a.b=new _.zd;a.c.push((0,_.t)(a.b.l,a.b));a.l=!1;_.Gd(a.b.h(),function(a){($d(this.g)||this.G)&&Eg(this);this.c.push(_.wa(_.F,a))},a)};_.g=_.Dg.prototype;_.g.sendMessage=function(a){this.ea(a.H)};_.g.ea=function(a){if(this.b){var b=new ug;_.B(b,1,a);_.Gd(this.b.h(),function(a){a.send(b)})}};
_.g.Za=function(a){this.h=a;_.ic(this,function(){this.h=null},this);Eg(this)};_.g.F=function(){return this};_.g.ha=function(a,b,c){this.a.ha(a,b,c)};_.Hg=function(a,b,c,d){_.Fg(a);Gg(a,b,c,d).then(function(a){var d=new sg;_.B(d,1,a.Ac);_.B(d,3,c);d=Cg((0,_.t)(this.v,this),d);d.connect(a.origin,b);this.b.b(d)},void 0,a)};Gg=function(a,b,c,d){var e=wg();b=(new yg("*",b,c,e,d)).g.a;a.c.push((0,_.t)(b.j,b));return b.then(function(a){return{Ac:e,origin:a}})};
_.Dg.prototype.I=function(a,b){if(_.A(a,2)==tg.cb||_.A(a,2)==tg.Pa)_.F(this.a),this.a=null,this.b.b(Cg((0,_.t)(this.v,this),a,b))};_.Dg.prototype.v=function(a){this.j.push(a);this.D()};_.Dg.prototype.D=function(){for(;Ig(this););};var Ig=function(a){if(a.O||!a.l||0==a.j.length)return!1;var b=_.A(a.j.shift(),1);a.h&&a.h.ea(b);_.L(a,new rg(b[0],b));return!0},Eg=function(a){a.l||(a.l=!0,a.b&&_.Gd(a.b.h(),function(a){a.c();_.ye(this.D,0,this)},a))}; _.Dg.prototype.listen=function(a,b,c,d){Eg(this);return _.Dg.C.listen.call(this,a,b,c,d)};_.Dg.prototype.Ma=function(a,b,c,d){Eg(this);return _.Dg.C.Ma.call(this,a,b,c,d)};_.Dg.prototype.J=function(a){Eg(this);return _.Dg.C.J.call(this,a)};
var Jg=function(a,b){this.g=a;this.b=b;this.constructor.ib||(this.constructor.ib={});this.constructor.ib[this.toString()]=this};Jg.prototype.toString=function(){this.a||(this.a=this.g.a+":"+this.b);return this.a};var Kg=function(a,b){Jg.call(this,a,b)};_.r(Kg,Jg);var Lg=function(a){this.a=a};new Lg("lib");var Mg,Tg,Ug,Vg;_.Ng=function(a){_.E.call(this);this.c={};this.j={};this.l={};this.a={};this.g={};this.J={};this.v=a?a.F():new _.K;this.S=!a;this.b=null;a?(this.b=a,this.l=a.l,this.a=a.a,this.j=a.j,this.g=a.g):(0,_.m)();a=Mg(this);this!=a&&(a.h?a.h.push(this):a.h=[this])};_.r(_.Ng,_.E);_.Og=.05>Math.random();Mg=function(a){for(;a.b;)a=a.b;return a};_.Ng.prototype.get=function(a){var b=_.Pg(this,a);if(null==b)throw new Qg(a);return b};
_.Pg=function(a,b){for(var c=a;c;c=c.b){if(c.O)throw Error("x");if(c.c[b])return c.c[b][0];if(c.J[b])break}if(c=a.l[b]){c=c(a);if(null==c)throw Error("y`"+b);_.V(a,b,c);return c}return null};
_.Ng.prototype.G=function(a,b){var c=_.Pg(this,a);if(null==c){if(this.g[a]){var d=this.g[a].h();_.Gd(d,(0,_.t)(this.G,this,a,b));return d}throw new Rg(a,b,"Module loaded but service or factory not registered with app contexts.");}return c.Ra?(d=new _.zd,_.Hd(d,c.Ra()),d.b(c),_.Gd(d,(0,_.t)(this.w,this,a)),d):this.w(a)};_.Ng.prototype.w=function(a){this.g[a]&&delete this.g[a];return this.get(a)};_.Ng.prototype.K=function(a,b,c){return c instanceof _.Ad?c:new Sg(a,b,c)};
_.V=function(a,b,c){if(a.O)_.F(c);else{a.c[b]=[c,!0];for(var d=Tg(a,a,b),e=0;e<d.length;e++)d[e].b(null);delete a.j[b];return c}};Tg=function(a,b,c){var d=[],e=a.a[c];e&&(_.Ya(e,function(a){var c;a:{for(c=a.Qa;c;){if(c==b){c=!0;break a}c=c.b}c=!1}c&&(d.push(a.d),_.fb(e,a))}),0==e.length&&delete a.a[c]);return d};Ug=function(a,b){a.a&&Jc(a.a,function(a,d,e){_.Ya(a,function(d){d.Qa==b&&_.fb(a,d)});0==a.length&&delete e[d]})};
_.Ng.prototype.I=function(a,b){var c=this.a&&this.a[a];if(c){for(var d=0;d<c.length;++d)if(c[d].Qa==this&&c[d].d==b){_.eb(c,d);break}0==c.length&&delete this.a[a]}};_.Ng.prototype.B=function(){if(Mg(this)==this){var a=this.h;if(a)for(;a.length;)a[0].W()}else for(var a=Mg(this).h,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&a[0].W&&a[0].W();this.c=null;this.S&&this.v.W();Ug(this,this);this.a=null;_.F(this.N);this.J=this.N=null;_.Ng.C.B.call(this)};
_.Ng.prototype.F=function(){return this.v};var Qg=function(a){_.Fa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};_.r(Qg,_.Fa);var Sg=function(a,b,c){_.Fa.call(this);this.message='Module "'+b+'" failed to load when requesting the service "'+a+'" [cause: '+c+"]";this.stack=c.stack+"\nWRAPPED BY:\n"+this.stack};_.r(Sg,_.Fa);var Rg=function(a,b,c){_.Fa.call(this);this.message='Configuration error when loading the module "'+b+'" for the service "'+a+'": '+c};_.r(Rg,_.Fa); Vg=new Lg("fva");_.Wg=new Kg(Vg,1);

}catch(e){_._DumpException(e)}
try{
var fp=/\s*;\s*/,gp=function(){return[]},hp=function(a){a=(a.a.cookie||"").split(fp);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}},ip=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.da[c[0]].prototype[a].apply(this,arguments)}:b[a].Nb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=
this.a[c[e]];if(n=n?n[a].apply(n,d):this.da[c[e]].prototype[a].apply(this,d)){d=n;break a}}d=!1}return d}:b[a].Mb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=this.a[c[e]],n=n?n[a].apply(n,d):this.da[c[e]].prototype[a].apply(this,d);if(null!=n){d=n;break a}}d=void 0}return d}:b[a].bc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var n=this.a[c[e]];n?n[a].apply(n,d):this.da[c[e]].prototype[a].apply(this,d)}}:
e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],n=0;n<c.length;++n){var q=this.a[c[n]];e.push(q?q[a].apply(q,d):this.da[c[n]].prototype[a].apply(this,d))}return e}:d||b[a].Nb||b[a].Mb||b[a].bc?e=null:e=gp;return e},jp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e},kp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Aa(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},
lp=[1],mp=function(a,b){return a.g.get(b)},np=function(a){this.a=a||{cookie:""}};_.g=np.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("r`"+a);if(/[;\r\n]/.test(b))throw Error("s`"+b);_.p(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(fp),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.p(this.get(a));this.set(a,"",0,b,c);return d};_.g.V=function(){return hp(this).keys};_.g.T=function(){return hp(this).values};_.g.clear=function(){for(var a=hp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var op=function(a){return this.Sa.c(a)},pp=function(a){_.z(this,a,"ci:ec",null)};
_.r(pp,_.y);pp.messageId="ci:ec";
var qp={a:_.bf,w:_.cf,l:_.df,v:_.ef,A:_.ff,G:_.gf},rp=function(a){var b=a.pa,c=function(a){c.C.constructor.call(this,a);var b=this.da.length;this.a=[];for(var d=0;d<b;++d)this.da[d].Oc||(this.a[d]=new this.da[d](a))};_.r(c,b);for(var d=[];a;){if(b=a.pa){b.da&&kp(d,b.da);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ya(e[f])&&e[f]!==b){var h=!!e[f].Lb,k=jp(f,e,d,h);(h=ip(f,e,k,h))&&(c.prototype[f]=h)}}a=a.C&&a.C.constructor}c.prototype.da=d;return c},sp=function(a){_.z(this,a,"capi:r_rstr",
null)};_.r(sp,_.y);sp.messageId="capi:r_rstr";var tp=function(a){_.z(this,a,"capi:r_recl",null)};_.r(tp,_.y);tp.messageId="capi:r_recl";var up=function(a){_.z(this,a,"capi:r_clre",null)};_.r(up,_.y);up.messageId="capi:r_clre";var vp=function(a){_.z(this,a,0,lp)};_.r(vp,_.y);var wp=function(a){_.z(this,a,"uv_r_hrd",null)};_.r(wp,_.y);wp.messageId="uv_r_hrd";var xp=function(a){_.z(this,a,"uv_r_rrr",null)};_.r(xp,_.y);xp.messageId="uv_r_rrr";var yp=function(a){_.z(this,a,"uv_r_rdr",null)};_.r(yp,_.y);
yp.messageId="uv_r_rdr";var zp=function(a){_.z(this,a,"uv_r_rdm",null)};_.r(zp,_.y);zp.messageId="uv_r_rdm";
var Ap=function(a,b,c){if(!this.Sa){for(var d=this.constructor;d&&!d.pa;)d=d.C&&d.C.constructor;d.pa.lb||(d.pa.lb=rp(d));this.Sa=new d.pa.lb(this);this.c||(this.c=op)}var e=this.Sa.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==e.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var d=(new np(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!_.db(f,d)&&h.test(d)&&
(e=_.vf(e),e=_.vf("https://"+d+e.a).toString())}this.oa=e;this.g=c||new pp;a.notificationsOnly&&_.B(this.g,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=mp(new _.O(window.location.href),"authuser"),null!=c&&(this.b=c));this.l=a.clientUrl||"notifierclient";c=mp(_.vf(this.l),"authuser");null!=c&&(this.b=c);this.Bb=a.propertyName||"Google Talk";this.G=a.cssUrl;this.locale=a.locale;this.A=a.debug;this.bb=a.userJid;this.Ha=a.uiVersion;this.Wb=null!=a.rosterExpanded?a.rosterExpanded:!0;this.Z=
a.hostLogMinValue;this.Ea=a.hideChat;this.Qb=a.refresh;this.N=a.hideProfileCard;this.Y=a.hideStatusMsgs;this.U=a.hideRosterOptions;this.S=a.hideRecentConversations;this.M=a.hideOTR;this.Kb=a.hostServerMessageCallback||!1;this.ca=a.isCentralRoster;this.Pb=a.isFullFrame||!1;this.Vb=a.rosterClass||"talk_roster";this.Xb=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.Da=
a.parentToken;this.Tb=b||!1;this.v=_.p(a.isRtl)?a.isRtl:_.kc.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var k in qp)b.push(qp[k].H)}this.D=a.entityId;this.Ia=a.useQuasarPanels||!1;this.Fa=a.silent||!1;this.Ob=a.ignoreCentralRoster||!1;this.Sb=a.lazy||!1;this.Jb=a.handleProfileLinks||!1;this.$=a.hostSettings;this.j=a.screen;this.J=a.docsConfig;this.Rb=a.jsmode;this.na=a.moleWidth;this.ia=a.moleHeight;this.ga=a.minimizedMoleHeight||36;this.Yb=a.derp;this.Ga=window.location.protocol+
"//"+window.location.host;this.h="";this.K=a.optOutAllowed;this.I=a.legacyTalkSignedIn;this.fb=a.useSpareMole;this.w=a.conversationId};Ap.pa=_.Ze;var Bp=function(a){_.z(this,a,0,null)};_.r(Bp,_.y);var Cp=function(a){_.z(this,a,0,null)};_.r(Cp,_.y);var Dp=function(a){_.z(this,a,0,null)};_.r(Dp,_.y);var Ep=function(a){_.z(this,a,0,null)};_.r(Ep,_.y);
var Fp=function(a,b){_.B(a,11,b)},Gp=function(a){return null==_.A(a,8)?"0":_.A(a,8)},Hp=function(a,b){_.B(a,4,b)},Ip=function(a,b){_.B(a,3,b)},Jp=function(a){_.z(this,a,"h_cc",null)};_.r(Jp,_.y);Jp.messageId="h_cc";
var Kp=function(a,b,c){_.ud(a,b,c,null)||_.bd(_.wa(b,a))},Lp=function(a){return new _.I(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},k=0,n;k<a.length;k++)n=a[k],Kp(n,_.wa(f,k),h);else b(e)})},Mp=function(a){_.fa();if(a[_.aa.Symbol.iterator])return a[_.aa.Symbol.iterator]();var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};
var Np=function(a){this.a=a;_.x||(delete this.a.lpu,delete this.a.ppu)},Op=["cn","tp"],Pp=function(a,b){var c;if(_.ya(window.document.postMessage)||_.ya(window.postMessage)||_.x&&window.postMessage)c=1;else if(_.zb)c=2;else{var d;if(d=_.x){d=!1;try{c=window.opener,window.opener={},d=_.Pd(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new Np(d)};_.va("GTalk_IFrameChannelConfig.build",Pp);
var Qp=function(a,b,c,d,e){_.E.call(this);this.a=a;this.b=d||window.document;this.g=new _.M(this);_.H(this,this.g);var f=_.ib;d=new _.O(a.oa+a.l);var h=a.g;null!=_.A(h,2)&&_.A(h,2)||(_.P(d,"ts","0"),_.P(d,"re",a.Wb),_.P(d,"ref",a.Qb));_.P(d,"client","sm");_.P(d,"prop",a.Bb);_.P(d,"nav","true");_.P(d,"fid",a.a);a.A&&_.P(d,"debug",a.A);_.P(d,"os",_.Cb);_.P(d,"stime",c);a.Ea&&_.P(d,"hc",a.Ea);for(c=0;c<Op.length;++c);b=_.Zb(b.a);_.P(d,"xpc",b);_.P(d,"ec",_.Zb(a.g.H));a.j&&_.P(d,"screen",a.j);-1!=f.indexOf("MSIE")&&
_.P(d,"ua",f);a.Da&&_.P(d,"pvt",a.Da);a.Kb&&_.P(d,"hsmc","true");_.p(a.Z)&&_.P(d,"logl",a.Z);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.P(d,"href",b.join("?")));b=new _.O(window.location.href);"false"==mp(b,"uacheck")&&_.P(d,"uacheck",!1);(f=a.Rb)&&_.P(d,"jsmode",f);(f=mp(b,"cssmode"))&&_.P(d,"cssmode",f);(f=mp(b,"convid"))&&_.P(d,"convid",f);if(f=b.g.T("convp"))_.Ba(f)||(f=[String(f)]),_.Bf(d.g,"convp",f);(f=mp(b,"smexp"))&&_.P(d,
"smexp",f);f=b.g.T("mods");a.Sb&&f.push("lazy");e&&(f=_.gb(f,e));0<f.length&&_.P(d,"mods",f.join(","));if(!a.oa||0>a.oa.indexOf("/u/"))(e=mp(b,"authuser"))?_.P(d,"authuser",e):null!=a.b&&_.P(d,"authuser",a.b);e=mp(b,"eid");_.Ia(_.Ta(e))||_.P(d,"eid",e);_.Ia(_.Ta(this.a.D))||_.P(d,"eid",this.a.D);null!=this.a.position&&_.P(d,"pos",this.a.position);_.p(a.Ha)&&_.P(d,"uiv",this.a.Ha);a.G&&_.P(d,"css",a.G);e=a.locale||mp(b,"hl");null!=e&&_.P(d,"hl",e);_.p(a.bb)&&_.P(d,"uj",a.bb);null!=a.N&&_.P(d,"hpc",
a.N);null!=a.Y&&_.P(d,"hsm",a.Y);null!=a.U&&_.P(d,"hro",a.U);null!=a.S&&_.P(d,"hrc",a.S);null!=a.M&&_.P(d,"hotr",a.M);null!=a.ca&&_.P(d,"pop",a.ca);a.Tb&&_.P(d,"pal","1");null!=a.Ia&&_.P(d,"uqp",a.Ia);null!=a.K&&_.P(d,"gooa",a.K);null!=a.I&&_.P(d,"gltsi",a.I);null!=a.fb&&_.P(d,"gusm",a.fb);null!=a.Fa&&_.P(d,"sl",a.Fa);a.Ob&&_.P(d,"icr","1");a.Jb&&_.P(d,"hpl","1");a.$&&_.P(d,"hs",a.$);a.J&&_.P(d,"dc",_.Zb(a.J.H));null!=a.na&&_.P(d,"molew",a.na);null!=a.ia&&_.P(d,"moleh",a.ia);null!=a.ga&&_.P(d,"mmoleh",
a.ga);a.Yb&&_.P(d,"derp","1");a.h&&_.P(d,"fcho",a.h);null!=a.Ga&&_.P(d,"two",a.Ga);null!=a.w&&_.P(d,"convid",a.w);_.P(d,"host","1");_.P(d,"zx",_.Ua());this.c=d.toString()};_.r(Qp,_.E);
var Rp=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Vb,a.b.body.appendChild(e));a=(0,_.t)(function(){var a="";this.a.Pb||(a="height:400px");var b=this.b.createElement("iframe");_.vc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});_.tc("talk_loading_msg",e)||_.yc(e);e.appendChild(b);var k=this.b.getElementById(this.a.a);_.We(this.g,k,["load","error"],function(a){k.contentWindow.postMessage("AllowFrame: Chat","*");d(a)}); k.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var Sp=new _.N("p"),Tp=new _.N("q"),Up=new _.N("r");var Vp=function(a){_.K.call(this);this.a=a};_.r(Vp,_.K);var Wp=function(a){_.M.call(this);var b=a.get(Up);this.a=new Vp(a.get(_.Mf));this.listen(b.F(),"h_opc",this.g);this.listen(b.F(),"h_sc",this.c);this.listen(b.F(),"h_po",this.j);this.listen(b.F(),"h_icr",this.b)};_.r(Wp,_.M);Wp.prototype.g=function(a){var b=this.a;a=_.C(new _.Sf(a.L),_.Qf,1);var c=new _.Sf;_.D(c,1,a);b.a.ea(c.H)};Wp.prototype.c=function(a){var b=this.a;a=_.A(new _.Tf(a.L),1);var c=new _.Tf;_.B(c,1,a);b.a.ea(c.H)}; Wp.prototype.j=function(a){var b=this.a;a=_.A(new _.Uf(a.L),1);var c=new _.Uf;_.B(c,1,a);b.a.ea(c.H)};Wp.prototype.b=function(a){var b=this.a;a=(new _.Rf(a.L)).a();var c=new _.Rf;_.B(c,1,a);b.a.ea(c.H)};
var Xp=function(a){_.z(this,a,"h_rha",null)};_.r(Xp,_.y);Xp.messageId="h_rha";var Yp=function(a,b){_.E.call(this);this.a=new _.M(this);_.H(this,this.a);this.a.listen(a.F(),"h_ssf",function(a){a=_.A(new _.Xf(a.L),1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new Xp;_.B(c,1,1);a.ea(c.H)};_.r(Yp,_.E);
var Zp=function(a){_.E.call(this);this.a=a.get(Up);_.H(this,new Yp(a.get(_.Mf),(0,_.t)(this.b,this)))};_.r(Zp,_.E);Zp.prototype.b=function(a){var b=new _.Xf;a&&(a=JSON.stringify(a),_.B(b,1,a));this.a.sendMessage(b)};var $p=function(a){_.M.call(this);this.b=a.get(Up);this.listen(this.b.F(),"uv_i_sc",this.g);this.a=null};_.r($p,_.M);$p.prototype.g=function(a){if(this.a){var b="idle";1==_.A(new _.Df(a.L),1)&&(b="active");this.a(b)}};var aq=function(a){_.K.call(this);this.a=a.get(Up);a=new _.M(this);_.H(this,a);a.listen(this.a.F(),"uv_r_frm",this.b);a.listen(this.a.F(),"uv_r_rdm",this.c)};_.r(aq,_.K);aq.prototype.reload=function(a){var b=new _.Ff;_.B(b,1,a);this.a.sendMessage(b)};aq.prototype.b=function(a){a=new _.Gf(a.L);_.L(this,new bq(!!_.A(a,1)))};aq.prototype.c=function(a){a=new zp(a.L);_.L(this,new cq(_.A(a,1)))};var bq=function(a){_.J.call(this,"uv_r_frm");this.a=a};_.r(bq,_.J); var cq=function(a){_.J.call(this,"uv_r_rdm");this.a=a};_.r(cq,_.J);
var dq=function(a){var b=_.l.GTalkNotifier;return b?_.jd(b):new _.I(function(c,d){var e=_.ye(function(){return d("chat.host.Client is not available!")},25E3),f=window.document.createElement("SCRIPT");f.src=_.Wf(a);f.addEventListener("load",function(){_.ze(e);(b=_.l.GTalkNotifier)?c(b):d("chat.host.Client is not available!")});f.addEventListener("error",function(){_.ze(e);d("chat.host.Client is not available!")});window.document.body.appendChild(f)})};
var eq=function(a){_.K.call(this);this.a=a.get(_.T);a=new _.M(this);_.H(a,a);a.listen(this.a.F(),"capi:r_clre",this.h);a.listen(this.a.F(),"capi:r_rrst",this.b);a.listen(this.a.F(),"capi:r_rers",this.c)};_.r(eq,_.K);eq.prototype.h=function(a){a=new up(a.L);_.L(this,new fq(_.C(a,vp,1)))};eq.prototype.c=function(){_.L(this,"I")};eq.prototype.b=function(){_.L(this,"H")};var fq=function(a){_.J.call(this,"G");this.a=a};_.r(fq,_.J);
var gq=function(a){_.M.call(this);this.a=a.get(_.Of);this.b=a.get(Sp);this.listen(this.b,"uv_r_rdm",this.Hb);this.listen(this.b,"uv_r_frm",this.Gb);this.listen(this.a,"G",this.nc);this.listen(this.a,"H",this.Fb);this.listen(this.a,"I",this.Ib)};_.r(gq,_.M);_.g=gq.prototype;_.g.nc=function(a){a=a.a;this.b.reload(a?[a.H]:[void 0])};_.g.Fb=function(){var a=this.b,b=new yp;a.a.sendMessage(b)};_.g.Gb=function(a){var b=this.a;a=!!a.a;var c=new tp;_.B(c,1,!!a);b.a.sendMessage(c)}; _.g.Hb=function(a){if(a.a&&(a=a.a[0])){a=new vp(a);var b=this.a,c=new sp;_.D(c,1,a);b.a.sendMessage(c)}};_.g.Ib=function(){var a=this.b,b=new xp;a.a.sendMessage(b)};
var hq=function(a){return new _.I(function(b,c){_.Ge(_.wf(a,"/webchat/extension-start"),function(a){_.Qe(a.target)||c();a=JSON.parse(_.Re(a.target));b(new _.Zf(a))})})};var iq=new _.N("s");var jq=function(a){_.J.call(this,a[0]);this.L=a};_.r(jq,_.J);var lq=function(a,b,c){_.E.call(this);this.v=(0,_.m)();var d={},e;e=null==_.A(a,1)?"hangouts.google.com":_.A(a,1);var f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=_.A(a,2)&&27!=_.A(a,2)&&(f="http://"));-1!=e.indexOf("talkgadget.")?(d.clientBaseUrl=f+e+"/talkgadget/_/",d.clientUrl="chat"):(d.clientBaseUrl=f+e+"/webchat/u/"+Gp(a)+"/",d.clientUrl="load");d.authUser=Gp(a);d.propertyName=_.Cf(_.A(a,2));d.locale=_.A(a,4);d.hideProfileCard=!0;d.parentToken=_.A(a,3);e=null==_.A(a,6)?!1:_.A(a,
6);d.isRtl=e;e=null==_.A(a,7)?!1:_.A(a,7);d.lazy=e;d.entityId=_.A(a,9);d.hostSettings=_.A(a,5);d.jsmode=_.A(a,11);e=null==_.A(a,13)?!1:_.A(a,13);d.isFullFrame=e;e=null==_.A(a,12)?"talk_roster":_.A(a,12);d.rosterId=e;e=null==_.A(a,15)?"gtn-roster-iframe-id-b":_.A(a,15);d.rosterIframeIdB=e;e=null==_.A(a,16)?!1:_.A(a,16);d.derp=!!e;e=_.C(a,Bp,14);null!=e&&(f=null==_.A(e,1)?!1:_.A(e,1),d.isCentralRoster=f,e=null==_.A(e,2)?!1:_.A(e,2),d.useQuasarPanels=e);e=_.C(a,Ep,10);null!=e&&(d.moleManagerLeftMargin=
_.A(e,1),d.moleManagerMiddleMargin=_.A(e,2),d.moleManagerRightMargin=_.A(e,3),d.moleManagerNoMoleAreaMargin=_.A(e,4),d.moleManagerBoundingElementId=_.A(e,5),d.moleWidth=_.A(e,6),d.moleHeight=_.A(e,7),d.minimizedMoleHeight=_.A(e,8));e=_.C(a,Dp,18);null!=e&&(f=null==_.A(e,1)?!0:_.A(e,1),d.optOutAllowed=f,f=_.C(e,Cp,3),null!=f&&(f=null==_.A(f,1)?!0:_.A(f,1),d.legacyTalkSignedIn=f),e=_.A(e,4),null!=e&&(d.useSpareMole=e));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new pp;_.B(e,2,
!0);_.B(e,1,!0);_.B(e,3,!1);d.endpointConfig=e;e=null==_.A(a,17)?!1:_.A(a,17);d.ignoreAutomatedRoster=e;d.conversationId=_.A(a,19);this.g=d;this.g.hostCallback=c;a=this.a=new Ap(this.g,!0,this.g.endpointConfig);f=this.a.oa;c=this.a.b;if(-1!=f.indexOf("talkgadget."))if(d=_.vf(f),e=d.a,0<=e.indexOf("/u/"))c=f;else{f=e.lastIndexOf("_/");if(0>f||f!=e.length-2)e+="_/";d.a="/u/"+c+e;c=d.toString()}else c=f;a.oa=c;this.a.h=window.location.origin;this.b=null;this.l=new _.K;a=_.qb(this.g);a.endpointConfig=
this.a.g.H;this.h=new b(a,!0);this.j=new _.Dg;_.H(this,this.j);kq(this)};_.r(lq,_.E);lq.prototype.sendMessage=function(a){this.ea(a.H)};lq.prototype.ea=function(a){this.c("_h",a)};lq.prototype.Za=function(a){this.b=a;_.ic(this,function(){this.b=null},this)};lq.prototype.F=function(){return this.l};
var kq=function(a){var b=Pp(a.a.oa,a.a.a),b=new Qp(a.a,b,a.v,window.document);_.H(a,b);Rp(b,a.a.Xb,function(){},function(){return mq(a)})},mq=function(a){_.Hg(a.j,window.document.getElementById(a.a.a).contentWindow,"31ACFC0_","google.com");a.c("_addClientMessageCallback",function(b){a.b&&a.b.ea(b);_.L(a.l,new jq(b))});a.c("_rosterIframeLoaded")};lq.prototype.c=function(a,b){for(var c=[],d=1;d<arguments.length;d++)c.push(arguments[d]);this.h[a]&&this.h[a].apply(this.h,c)};
var nq=function(a){_.z(this,a,"capi:id_sc",null)};_.r(nq,_.y);nq.messageId="capi:id_sc";var oq=function(a){_.K.call(this);var b=new _.M(this);_.H(b,b);this.a=a.get(_.T)};_.r(oq,_.K);oq.prototype.b=function(a){var b=new nq;switch(a){case "idle":_.B(b,1,0);break;case "active":_.B(b,1,1)}this.a.sendMessage(b)};var pq=function(a){_.z(this,a,"h_ext",null)};_.r(pq,_.y);pq.messageId="h_ext";var rq=function(){_.M.call(this);_.S("Starting ...");_.og();this.a=new _.Ng;_.H(this,this.a);this.j=null;this.c=[];this.listen(window,"unload",this.W);this.g=new _.Hf(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));var a=_.A(this.g,1),b=new _.Dg;_.Fg(b);b.a=new _.xg((0,_.t)(b.I,b),a);b.a.ha("*",void 0,void 0);b.c.push(_.wa(_.F,b.a));this.b=b;_.V(this.a,Up,this.b);this.listen(this.b.F(),"uv_qm",this.l);qq(this)},sq;_.r(rq,_.M);
var tq=function(a,b){null==a.c?b():a.c.push(b)},qq=function(a){_.S("Initializing ...");_.nd(Lp([hq(_.A(a.g,2)).then(a.v,void 0,a),dq(a.g)]).then(function(b){var c=Mp(b);b=c.next().value;c=c.next().value;return uq(a,b,c)}).then(function(b){if(!a.O){b.Za(a.b);a.b.Za(b);a.j=b;_.V(a.a,_.T,a.j);_.V(a.a,_.Mf,a.j);_.V(a.a,Tp,a.j);_.H(a,new Wp(a.a));b=new $p(a.a);_.V(a.a,iq,b);var c=new oq(a.a);_.V(a.a,_.Lf,c);c=(0,_.t)(c.b,c);b.a=c;_.H(a,new Zp(a.a));b=new aq(a.a);_.V(a.a,Sp,b);_.V(a.a,_.Of,new eq(a.a));
new gq(a.a);for(a.b.sendMessage(new wp);a.c.length;)a.c.shift()();a.c=null}}),function(a){_.S("Failed to start : %s.",a||"")})};rq.prototype.v=function(a){var b=this;return new _.I(function(c,d){b.b.sendMessage(a);_.A(a,1)||d("Unauthenticated");c(a)})};
var uq=function(a,b,c){if(a.O)return null;var d=new Jp,e=_.vf(_.A(a.g,2)),f=e.b;null!=e.c&&(f+=":"+e.c);_.B(d,1,f);_.B(d,2,27);_.B(d,13,!0);_.B(d,17,!0);Ip(d,_.A(b,1));Fp(d,_.A(a.g,4));Hp(d,_.A(a.g,3)||"en");b=new Bp;_.B(b,2,!0);_.B(b,1,!0);_.D(d,14,b);return new lq(d,c,function(b,c){if("extensionMessage"==b){var d=new _.Ef;_.B(d,1,c);a.b.sendMessage(d)}})};
rq.prototype.l=function(a){a=new _.Ef(a.L);var b=new _.pg;_.qg(b,_.A(a,1));"onSendHostMessage"==b.a&&tq(this,(0,_.t)(function(){var a=new pq,d=b.content().toString();_.B(a,1,d);this.j.sendMessage(a)},this))};_.va("default_host._DumpException",function(a){return window.console.error(a.stack)});if(!_.p(sq)||null==sq||sq.O)sq=new rq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
