ExtensionDropdown=function(d){var j=$(d.body),m=d.getElementById("items"),p=d.getElementById("searchResults"),q=d.getElementById("recentSites"),x=d.getElementById("identitiesMenuItem"),ea=d.getElementById("matchingSitesTopLevel"),fa=d.getElementById("matchingSites"),y=$("#backButton"),J=$("#debugconsole"),K=$("#encryptedExportMenuItem"),L=$("#wifiExportMenuItem"),M=$("#matchingSitesMenuItem"),N=$("#recentSitesMenuItem"),g=$("#container"),r=$("#searchInput"),V=$("#applicationsMenuItem"),W=null,s=null,
t=null,u=null,z=null,A=null,B=null,X=null,C=!1,D=!1,O=!1,P=!1,Q={},f=null,E={},e=[],k={GroupState:function(a){var b=LPTools.getNavIndex();this.pop=function(){a.rebuildItems();LPTools.setNavIndex(b)}},SearchState:function(){var a=new k.CSSState("searchItem",{restoreKeyboardNav:!1});this.pop=function(){Y();a.pop()}},TopLevelMatchingSitesState:function(a){var b=new k.CSSState("matchingSites"),c=new k.GroupState(a);this.pop=function(){c.pop();b.pop()}}},v=j.attr("class");k.CSSState=function(a,b){var c=
v;j.removeClass(v);j.addClass(a);v=a;LPTools.getOption(b,"applyKeyboardNav",!0)&&LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"),{selectFirst:!0});this.pop=function(){j.removeClass(v);j.addClass(c);v=c;LPTools.getOption(b,"restoreKeyboardNav",!0)&&LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"));if(b&&"function"===typeof b.onPop)b.onPop()}};var Z=function(){LPTools.parseUserSpecificMenu(d.getElementById("mainMenu"),LPProxy.getAccountClass());$("#username").text(bg.g_username);
F()},F,aa=function(){g.LP_removeAttr("style");var a=g.outerHeight();LPPlatform.setDropdownPopoverSize(a,g.outerWidth());g.css("height",a);LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"))};F=function(){if(0===e.length)aa();else{var a=e[0].pop;e[0].pop=function(){a();aa()}}};var ba=function(a){var b;LPProxy.getPreference("showAcctsInGroups",!0)&&(a=LPProxy.assignItemsToGroups(a,!1),b={separateFavorites:!0});return new Container(a,b)},ca=function(a,b,c){for(var h=[],d=0,e=f.length;d<e;++d)h.push(new MatchingAccountDisplay(LPProxy.getSiteModel(f[d].aid)));
b=new Container(h,b);b.setElement(a);b.rebuildItems();c&&F()},Y=function(){LPTools.removeDOMChildren(p);for(var a=0,b=B.length;a<b;++a){var c=B[a],h=c.build();c.postBuild(h);p.appendChild(h)}0===B.length&&(a=LPTools.buildEmptyPlaceholder(Strings.translateString("No Matching Results"),"extensionSearchPlaceholder",p),p.appendChild(a));LPTools.addKeyBoardNavigation(p.children,{rightArrowSelector:".moreItem",selectFirst:!0})},R,S=null;R=function(a){0<a.length?(D&&(B=X.getSearchResultItems(a),Y()),C||
(e.push(new k.CSSState("search",{applyKeyboardNav:!1,onPop:function(){r.val("")}})),C=!0)):S&&0<S.length&&(w(),C=!1);S=a};var l=function(a,b){return function(){D?b():E[a]=b}},T=function(a){LPPlatform.openTabDialog("formFill",a)},da=function(a){a.appendChild(LPTools.createElement("li","extensionMenuItem none","None Available"))},w=function(){var a=e.pop();a&&a.pop()},U=function(){dialogs.generatePassword.getDialog().close();y.unbind("click",U)},G=null,H=function(a,b,c){a.isEmpty()&&(a=LPTools.createElement("div",
"emptyView"),a.appendChild(LPTools.createElement("img",{src:"images/vault_4.0/"+b,"class":"emptyViewIcon"})),a.appendChild(LPTools.createElement("h1","emptyViewText",c)),document.getElementById("items").appendChild(a))};r.LP_addSearchHandlers("inputDialog",function(a){R(a)});y.bind("click",w);$("[childview]").bind("click",function(a){for(var b=a.target,c=null;null!==b&&!(c=b.getAttribute("childview"),null!==c);)b=b.parentElement;e.push(new k.CSSState(c,void 0));a&&(a.stopPropagation(),a.preventDefault())});
$("#addSite").bind("click",function(a){bg.get_selected_tab_data_no_extension(null,function(a){bg.lpevent("m_add");LPPlatform.openTabDialog("site",{defaultData:{url:a?a.url:""}});LPPlatform.closePopup()});a.stopPropagation()});$("#saveAllEnteredData").bind("click",function(){bg.lpevent("m_saed");bg.saveall()});$("#addNote").bind("click",function(){bg.lpevent("m_addn");LPPlatform.openTabDialog("note",void 0)});$("#addFormFill").bind("click",function(){bg.lpevent("m_af");T()});$("#addCreditCard").bind("click",
function(){bg.lpevent("m_af");T({defaultData:{profiletype:FormFill.prototype.FORM_FILL_TYPE_CREDIT_CARD}})});$("#clearForms").bind("click",function(){bg.lpevent("m_clrf");bg.clearforms()});var I=null;$("#chooseProfile").bind("click",function(){dialogs.chooseProfile.open({preSetup:function(a){if(null===I){var b=dialogs.chooseProfile.parentElementID,c=a.options.hideHeader;I=function(){dialogs.chooseProfile.parentElementID=b;a.options.hideHeader=c;a.$element.css("min-height","")}}a.$element.css("min-height",
0);dialogs.chooseProfile.parentElementID="chooseProfileCreditCard";a.options.hideHeader=!0},onClose:function(){w()}})});$("#vaultMenuItem").bind("click",function(){bg.lpevent("m_ov");bg.openvault()});$("#sitesMenuItem").bind("click",l("sites",function(){t.rebuildItems(m);H(t,"Empty_Site.png",Strings.translateString("Remember every password"))}));$("#formFillsMenuItem").bind("click",l("formFills",function(){z.rebuildItems(m);H(z,"Empty_Form.png",Strings.translateString("Fill Every Form"))}));$("#applicationsMenuItem").bind("click",
l("applications",function(){A.rebuildItems(m);H(A,"Empty_Site.png",Strings.translateString("Remember every password"))}));$("#generateMenuItem").bind("click",function(){dialogs.generatePassword.open({preSetup:function(a){if(null===G){var b=dialogs.generatePassword.parentElementID,c=a.options.hideHeader,h=a.dynamicHeight;G=function(){dialogs.generatePassword.parentElementID=b;a.options.hideHeader=c;a.useDynamicHeignt(h)}}dialogs.generatePassword.parentElementID="extensionDropdownGeneratePassword";
a.options.hideHeader=!0;a.useDynamicHeignt(!1)},onClose:function(){w()},onCopy:function(){LPPlatform.closePopup(!0)}});y.unbind("click",U);y.bind("click",U)});$("#notesMenuItem").bind("click",l("notes",function(){u.rebuildItems(m);H(u,"Empty_Note.png",Strings.translateString("Store Every Note"))}));$("#clearMostRecent").bind("click",function(){bg.clearrecent();LPTools.removeDOMChildren(q);da(q)});var n=l("mostRecent",function(){if(!O){var a=bg.getClearRecentTime(),b=bg.lpGetPref("recentUsedCount",
10),c=t.getItemChildren().concat(u.getItemChildren());c.sort(VaultItemBaseDisplay.prototype.sortByMostRecent);for(var h=[],d=0,e=c.length;d<e&&d<b;++d){var g=c[d];g.getLastTouchValue()>=a&&h.push(g._model.newDisplayObject())}0<h.length?(new Container(h,{sortFunction:VaultItemBaseDisplay.prototype.sortByMostRecent})).initialize(q):da(q);O=!0}LPTools.addKeyBoardNavigation(q.children,{rightArrowSelector:".moreItem",selectFirst:!0})});N.bind("click",n);n=l("matchingSites",function(){P||(ca(fa),P=!0);
LPTools.addKeyBoardNavigation(d.getElementById("matchingSites").children,{rightArrowSelector:".moreItem",selectFirst:!0})});M.bind("click",n);$("#prefMenuItem").bind("click",function(){bg.lpevent("m_op");bg.openprefs()});$("#helpMenuItem").bind("click",function(){bg.lpevent("m_oh");bg.openhelp()});$("#adminConsoleMenuItem").bind("click",function(){bg.lpevent("m_oec");bg.openentconsole()});$("#logoutMenuItem").bind("click",function(){bg.lpevent("m_lo");bg.loggedOut(!1,"menu")});$("#challengeMenuItem").bind("click",
function(){bg.lpevent("m_sec");bg.openseccheck()});$("#favoritesMenuItem").bind("click",function(){bg.lpevent("m_of");bg.openfavorites()});$("#aboutMenuItem").bind("click",function(){bg.lpevent("m_abt");bg.openabout()});J.bind("click",function(){bg.lpevent("m_dbgcon");bg.opendebugtab()});LPPlatform.setupDropdownImportMenu(g);$("#csvExportMenuItem").bind("click",function(){bg.lpevent("m_e");bg.openexport()});$("#formFillExportMenuItem").bind("click",function(){bg.lpevent("m_eff");bg.formfillexport()});
K.bind("click",function(){bg.lpevent("m_elp");bg.openlastpassexport()});L.bind("click",function(){bg.lpevent("m_ewlan");bg.wlanexport()});$("#printSitesMenuItem").bind("click",function(){bg.lpevent("m_p");bg.openprint(!1)});$("#printNotesMenuItem").bind("click",function(){bg.lpevent("m_pn");bg.openprint(!0)});$("#refreshMenuItem").bind("click",function(){bg.lpevent("m_ref");LPProxy.refreshSites()});$("#clearCachMenuItem").bind("click",function(){bg.lpevent("m_cl");bg.clearCache(!1,!0,!1)});$("#myAccountMenuItem").bind("click",
function(){bg.lpevent("m_mya");bg.openmyaccount()});$("#sessionsMenuItem").bind("click",function(){bg.lpevent("m_ses");bg.opensessions()});LPPlatform.addEventListener(window,"unload",function(){Topics.get(Topics.CLEAR_DATA).publish()});j.on("click",".extensionMenuItem, .footer",function(){LPPlatform.closePopup()});LPFeatures.allowGift()&&(n=$("#specialOfferMenuItem"),n.show(),n.bind("click",function(){bg.openURL(LPProxy.getBaseURL()+"gift.php")}));Topics.get(Topics.PUSH_STATE).subscribe(function(a){e.push(a)});
Topics.get(Topics.EDIT_SITE).subscribe(function(a){a.vaultItem=a.vaultItem.getID();LPPlatform.openTabDialog("site",a)});Topics.get(Topics.EDIT_NOTE).subscribe(function(a){a.vaultItem=a.vaultItem.getID();LPPlatform.openTabDialog("note",a)});Topics.get(Topics.EDIT_FORM_FILL).subscribe(function(a){a.vaultItem=a.vaultItem.getID();T(a)});Topics.get(Topics.EDIT_APPLICATION).subscribe(function(a){a.vaultItem=a.vaultItem.getID();LPPlatform.openTabDialog("application",a)});Topics.get(Topics.IDENTITY_ENABLE).subscribe(function(a){LPProxy.enableIdentity(a);
W=a});Topics.get(Topics.CONFIRM).subscribe(function(a){LPPlatform.openDropdownPopoverDialog("confirmation",a)});Topics.get(Topics.REPROMPT).subscribe(function(a){LPPlatform.openDropdownPopoverDialog("reprompt",{successCallback:a})});Topics.get(Topics.LEFT_ARROW).subscribe(function(){LPTools.disableMouse();w()});Topics.get(Topics.CLEAR_DATA).subscribe(function(){for(var a=e.length-1;-1<a;--a)e[a].pop();e=[];LPTools.setNavIndex(0);r.val("");P=O=D=C=!1;Q={};E={};f=null;G&&G();I&&I();g.removeClass("initialized")});
return{translate:function(){Strings.translateStrings(Strings.Vault);Strings.translate(d.body);LPFeatures.updateFeatures({"import":!0,noexport:!1,show_notes:!0,hideidentities:!1})},setup:function(){g.addClass("loading");J.LP_removeAttr("style");K.LP_removeAttr("style");L.LP_removeAttr("style");V.LP_removeAttr("style");bg.is_user_debug_enabled()&&J.show();bg.have_binary()&&(K.show(),bg.g_is_win&&L.show());LPTools.hasProperties(bg.g_applications)&&V.show();f=bg.getmatchingsites(!1,!0,!1);for(var a=0,
b=f.length;a<b;++a)Q[f[a].aid]=!0;(a=LPProxy.getPreference("toplevelmatchingsites",!1))||0===f.length?(M.LP_removeAttr("style"),N.addClass("divider")):(M.show(),N.removeClass("divider"));a?l("topLevelMatchingSites",function(){ca(ea,{autoExpandSingleItem:!1,moreOptionsElement:d.getElementById("matchingSites"),moreOptionsState:k.TopLevelMatchingSitesState,addLastClass:!1},!0)})():0<f.length&&$("#matchingSiteCounter").text(f.length);Z();g.addClass("initialized");r.focus();setTimeout(function(){LPProxy.initializeModel();
s=LPProxy.getIdentities();LPProxy.enableCurrentIdentity(s);if(0<s.length){var a=W,a=Strings.translateString("Identities")+" ("+a.getName()+")",b=x.firstChild;3!==b.nodeType?(b=d.createTextNode(a),x.insertBefore(b,x.firstChild)):b.textContent=a;for(var a=[],b=0,e=s.length;b<e;++b)a.push(s[b].newDisplayObject());(new IdentityContainer(a)).initialize(d.getElementById("identities"))}else $(x).hide();t=ba(LPProxy.getSites());t.setElement(m);u=ba(LPProxy.getNotes());u.setElement(m);z=new Container(LPProxy.getFormFills());
z.setElement(m);A=new Container(LPProxy.getApplications());A.setElement(m);for(var a=new Container(LPProxy.getAllItems()),b=function(){Topics.get(Topics.PUSH_STATE).publish(new k.SearchState)},e=a.getItemChildren(),f=0,l=e.length;f<l;++f)e[f].pushState=b;X=a;D=!0;g.removeClass("loading");for(var j in E)E[j]();(j=r.val())&&R(j);F()},0)},setupUserSpecific:Z,State:k,isMatchingSite:function(a){return!0===Q[a]}}}(document);
