LPServer=function(){var m=null,d=null,r,s=function(a,b){var c=a,e={},d;for(d in c){var f=c[d];if("object"===typeof f)for(var j in f)e[d+"["+j+"]"]=f[j];else e[d]=f}a=e;b=b||"";var c=[],g;for(g in a)e=a[g],"object"===typeof e?c=c.concat(s(e,g)):(b&&(g=b+"["+g+"]"),c.push(g+"="+encodeURIComponent(e)));return c};r=function(a){return s(a).join("&")};var t=function(a){var b=r(a.data),c=new XMLHttpRequest;a.success&&(c.onload=function(){if(4===c.readyState)if(200===c.status)switch(a.dataType){case "xml":a.success(c.responseXML,
c.responseText);break;case "json":var b=null;try{b=JSON.parse(c.responseText)}catch(e){}a.success(b,c.responseText);break;default:a.success(c.responseText)}else a.error&&a.error(c,c.statusText)});a.error&&(c.onerror=function(){a.error(c,c.statusText)});var e=a.url;"GET"===a.type&&0<b.length&&(e=a.url+"?"+b);c.open(a.type||"GET",e,!0);"POST"===a.type?(c.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),c.send(b)):c.send()},u=function(a){return function(){a()}},j=function(a,b,c,e){g(a,
b,c,e)||b.error(c)},g,v=function(a,b,c,e){return a&&(a=a[c],"function"===typeof a)?(a(e,b),!0):!1};g=function(a,b,c,e){a=v(a,b,c,e);return a=v(b.callbacks,b,c,e)||a};var w=function(a,b){try{h.logException(a)}catch(c){}a instanceof k?b.error(a.message):b.error()},A=function(a,b){return function(c,e){try{g(a,b,e)||(null===c&&e?b.error("invalidxml"):z(c,a,b))}catch(d){w(d,b)}}},l=function(a,b){var c=a.getElementsByTagName(b);return 0<c.length?c[0]:null},n=function(a,b){var c=l(a,b);return c?c.textContent:
""},z=function(a,b,c){var e=l(a,"result"),d=l(a,"ok"),f=l(a,"error"),h=l(a,"failed");if(e){var d=e.getAttribute("rc"),f=e.getAttribute("msg"),h=e.getAttribute("success"),k=e.getAttribute("ok");if(d){j(b,c,d,e);return}if(f){j(b,c,f,e);return}if(h){j(b,c,h,e);return}if(k){j(b,c,"ok");return}e=e.textContent.trim();if("ok"===e){if(!g(b,c,"ok")){j(b,c,n(a,"status"));return}}else if("bad"===e){c.error(n(a,"message"));return}}else{if(d){j(b,c,"ok",d);return}if(f){g(b,c,f.getAttribute("cause"),f)||j(b,c,
f.getAttribute("message"),f);return}if(h){j(b,c,h.getAttribute("reason"),h);return}}"function"===typeof c.error&&c.error()},B=function(a,b){return function(c,e){try{if(null===c&&e)b.error("invalidjson");else{if(c.error){j(a,b,c.error,c);return}if(c.res)if("success"===c.res){if(g(a,b,c.res,c))return}else{j(a,b,c.res,c);return}else if(g(a,b,c.reason,c)||g(a,b,c.status,c)||g(a,b,c.cmd,c))return}if(a&&"function"===typeof a["default"])a["default"](c,b);else"function"===typeof b.success&&b.success(c)}catch(d){w(d,
b)}}},p=function(a){a.userSupplied=a.userSupplied||{};a.type=void 0===a.type?"POST":a.type;a.url=h.getBaseURL()+a.url;if(a.userSupplied.requestArgs)for(var b in a.userSupplied.requestArgs)a.data[b]=a.userSupplied.requestArgs[b];a.userSupplied.error&&(a.error=u(a.userSupplied.error));if(a.data&&void 0===a.data.token&&(void 0===a.CSRFToken||a.CSRFToken)){if(null===m){b=a.userSupplied.error;h.ajax({type:"POST",url:h.getBaseURL()+"getCSRFToken.php",success:function(b){m=b;a.data.token=m;h.ajax(a)},error:u(b)});
return}a.data.token=m}h.ajax(a)},x=function(a,b){var c={};switch(typeof b.success){case "string":c[b.success]=b.userSupplied.success;b.success=a(c,b.userSupplied);break;case "function":c["default"]=b.success;b.success=a(c,b.userSupplied);break;default:if(b.callbacks||b.userSupplied&&(b.userSupplied.success||b.userSupplied.callbacks))b.success=a(b.callbacks,b.userSupplied)}},y=function(a,b,c){c=c||[];for(var e in b){var d=a[e],f=b[e];if("object"===typeof f)y(d,f,c.concat(e));else if(typeof d!==f)throw c.push(e),
"Extension is missing the following property: "+c.join(".")+" ("+f+")";}},q=function(a,b,c){a=a.getAttribute(b);return void 0===a?c:a},C={AES:{Encrypt:"function",Decrypt:"function",hex2bin:"function",bin2hex:"function"},enc:"function",dec:"function",RSAKey:"function",createRandomHexString:"function",parse_public_key:"function",parse_private_key:"function",enccbc:"function",make_lp_key_iterations:"function",make_lp_hash_iterations:"function"},D={RSAKey:!0},h={ajax:t,logException:function(){},hex2bin:function(){return d.AES.hex2bin.apply(d.AES,
arguments)},bin2hex:function(){return d.AES.bin2hex.apply(d.AES,arguments)},encryptAES:function(a,b){return 0<a.length?d.AES.Encrypt({pass:b,data:a,b64:!0,bits:256}):a},decryptAES:function(a,b){return d.AES.Decrypt({pass:b,data:a,b64:!0,bits:256})},encrypt:function(a,b){return d.enc(a,b)},decrypt:function(a,b){try{return d.dec(a,b)}catch(c){return""}},createRandomHexString:function(){return d.createRandomHexString.apply(d,arguments)},parsePublicKey:function(){return d.parse_public_key.apply(d,arguments)},
parsePrivateKey:function(a){if(!d.rsaprivatekeyhex)throw"rsaprivatekeyhex required for this action.";return d.parse_private_key(a,d.rsaprivatekeyhex)},encryptCBC:function(){return d.enccbc.apply(d,arguments)},makeKey:function(){return d.make_lp_key_iterations.apply(d,arguments)},makeHash:function(){return d.make_lp_hash_iterations.apply(d,arguments)},getBaseURL:function(){return d.base_url||""},getLocalKey:function(){return d.g_local_key},setLocalKey:function(a){d.g_local_key=a}},k=function(a){this.message=
a;this.stack=Error().stack};k.prototype=Object.create(Error.prototype);k.prototype.name="ClientException";k.prototype.constructor=k;return{ajax:t,getRecordsFromResponse:function(a,b,c){for(var e=[],d=0;d<c;++d)e.push(q(a,b+d));return e},jsonRequest:function(a){x(B,a);a.dataType="json";p(a)},xmlRequest:function(a){x(A,a);a.dataType="xml";p(a)},textRequest:function(a){a.dataType="text";p(a)},initialize:function(a,b){y(a,C);for(var c in b)h[c]=b[c];for(var e in D)h[e]=a[e];d=a},ext:h,isArray:function(a){return"[object Array]"===
Object.prototype.toString.call(a)},getNodes:function(a,b){return a.getElementsByTagName(b)},getNode:l,getNodeText:n,getAttr:q,getAttrInt:function(a,b,c){a=parseInt(q(a,b,c));return isNaN(a)?c:a},extendCallback:function(a,b){return function(){b.apply(window,arguments);a&&a.apply(window,arguments)}},ClientException:k,clearCSRFToken:function(){m=null}}}();
