LPServer.sharing=LPServer.sharing||{};
LPServer.sharing.individual=function(){var s=function(a,b,d){this.email=a;this.pubkey=b;this.encpass=d},r=function(a){var b=LPServer.ext.getLocalKey();this.aid=a.getAttribute("aid");this.username=LPServer.ext.decrypt(a.getAttribute("username"),b);this.password=LPServer.ext.decrypt(a.getAttribute("password"),b);this.name=LPServer.ext.decrypt(a.getAttribute("name"),b);this.grouping=LPServer.ext.decrypt(a.getAttribute("grouping"),b);this.extra=LPServer.ext.decrypt(a.getAttribute("extra"),b);this.attachkey=
LPServer.ext.decrypt(a.getAttribute("attachkey"),b);this.afids=this.parseFields(a.getAttribute("afids"));this.otherafids=this.parseFields(a.getAttribute("otherafids"));this.accts_notes=this.parseFields(a.getAttribute("accts_notes"));this.accts_usernames=this.parseFields(a.getAttribute("accts_usernames"));this.accts_passwords=this.parseFields(a.getAttribute("accts_passwords"))};r.prototype.parseFields=function(a){var b=[];if(a){a=a.split("^");for(var d=0,e=a.length;d<e;++d){var c=a[d];""!==c&&(c=a[d].split("&"),
b.push({name:c[0],value:LPServer.ext.decrypt(c[1])}))}}return b};var g=function(a,b){return a?LPServer.ext.encryptCBC(a,b):""},p=function(a,b){for(var d=0,e=a.length;d<e;++d)a[d].value=g(a[d].value,b);return a};r.prototype.encrypt=function(a){return{username:g(this.username,a),password:g(this.password,a),name:g(this.name,a),grouping:g(this.grouping,a),extra:g(this.extra,a),attachkey:g(this.attachkey,a),afids:p(this.afids,a),otherafids:p(this.otherafids,a),accts_notes:p(this.accts_notes,a),accts_usernames:p(this.accts_usernames,
a),accts_passwords:p(this.accts_passwords,a)}};var q=function(a,b,d,e){for(var c=0,f=d.length;c<f;++c)a[b+e+c+"name"]=d[c].name,a[b+e+c+"value"]=d[c].value;a[b+"num"+e]=d.length},t=function(a,b){var d=LPServer.getAttrInt(a,"numsharesok",0);if(0<d){for(var e=[],c=0;c<d;++c){var f=LPServer.getAttr(a,"emailok"+c,""),n=LPServer.getAttr(a,"emailokpubkeyhex"+c,""),k=LPServer.getAttr(a,"emailencp"+c,"");e.push(new s(f,n,k))}d=[];c=LPServer.getNodes(a,"encdata");f=0;for(n=c.length;f<n;++f)d.push(new r(c[f]));
c={cmd:"share",sharemessage:"",giveshare:b.params.giveshare?1:0,numemails:e.length,numaids:d.length,fromrole:0,sharesyncpush:0,shareautopull:0,reportname:[]};f=0;for(n=e.length;f<n;++f){var m=e[f],k=LPServer.ext.createRandomHexString(64),k=LPServer.ext.hex2bin(k),g=new LPServer.ext.RSAKey;LPServer.ext.parsePublicKey(g,m.pubkey);var h=g.encrypt(k),g="email"+f;c[g]=m.email;c["sharekeyenchex"+f]=h;c["sharekeyenchexsig"+f]="";m.encpass&&(c["encpass"+f]=m.encpass);for(m=0;m<d.length;++m){var h=d[m],l=
h.encrypt(k);1==b.params.logname&&c.reportname.push({aid:h.aid,name:h.name});var j=g+"aid"+m;c[j]=h.aid;c[j+"username"]=l.username;c[j+"password"]=l.password;c[j+"name"]=l.name;c[j+"grouping"]=l.grouping;c[j+"extra"]=l.extra;c[j+"attachkey"]=l.attachkey;q(c,j,l.afids,"afid");q(c,j,l.otherafids,"otherafid");q(c,j,l.accts_notes,"accts_notes");q(c,j,l.accts_usernames,"accts_usernames");q(c,j,l.accts_passwords,"accts_passwords")}}LPServer.xmlRequest({url:"showshare.php",data:c,success:"shareok",userSupplied:b})}else b.error();
e=LPServer.getAttrInt(a,"numsharesdne",0);0<e&&b.callbacks&&b.callbacks.invite&&b.callbacks.invite({emails:LPServer.getRecordsFromResponse(a,"emaildne",e)});e=LPServer.getAttr(a,"sharingwithself","");d=LPServer.getAttrInt(a,"numsharesinv",0);c=LPServer.getAttrInt(a,"numsharesuns",0);f=LPServer.getAttrInt(a,"numsharesspa",0);n=LPServer.getAttrInt(a,"numsharesres",0);(e||0<d||0<c||0<f||0<n)&&b.callbacks&&b.callbacks.problems&&b.callbacks.problems({withself:e,rowsINV:LPServer.getRecordsFromResponse(a,
"emailinv",d),rowsUNS:LPServer.getRecordsFromResponse(a,"emailuns",c),rowsSPA:LPServer.getRecordsFromResponse(a,"emailspa",f),rowsRES:LPServer.getRecordsFromResponse(a,"emailres",n)})},h=function(a,b,d){return LPServer.ext.encryptAES(LPServer.ext.decrypt(a,b),d)};return{shareItems:function(a){var b={cmd:"getclientdata",shareeusername:a.params.emails,numaids:1};if(LPServer.isArray(a.params.aids)){for(var d=0,e=a.params.aids.length;d<e;++d)b["aid"+d]=a.params.aids[d];b.numaids=a.params.aids.length}else b.aid0=
a.params.aids;LPServer.xmlRequest({url:"showshare.php",data:b,callbacks:{getclientdataack:t},userSupplied:a})},unshareItem:function(a){LPServer.xmlRequest({url:"showshare.php",data:{cmd:"unshare",aid:a.params.id,username:a.params.email},success:"unshareok",userSupplied:a})},acceptShare:function(a){var b=a.params.key,d=a.params.pendingShareKey,e=a.params.pendingShare,c={cmd:"acceptshare",msgtosharer:"",aid:e.id,newname:LPServer.ext.encryptAES(a.params.name,b),newgroup:LPServer.ext.encryptAES(a.params.group,
b),name:h(e.sharename,d,b),grouping:h(e.sharegroup,d,b),username:h(e.username,d,b),password:h(e.password,d,b),extra:h(e.extra,d,b),attachkey:h(e.attachkey,d,b)},f=e.save_all?"otherafid":"afid",g;for(g in e.shareafids){var k=e.shareafids[g];k&&(k=h(k,d,b));c[f+g]=k}LPServer.xmlRequest({url:"showacceptshare.php",data:c,success:"acceptshareok",userSupplied:a})},rejectShare:function(a){LPServer.xmlRequest({url:"showacceptshare.php",data:{cmd:"rejectshare",aid:a.params.id},success:"rejectshareok",userSupplied:a})}}}();
